// Spanish for client/i18n.js, keyed by the English the game writes. {0}, {1}... are holes (see i18n.js); a value can be
// a function of the translated holes when the Spanish needs a different shape. Unit model names (M4 Sherman,
// Panzer IV) stay as they are, like map names that are places.
export default {
  'Not enough carried ammunition': 'No hay suficiente munición a bordo',
  "Supply Truck": "Camión de suministros",
  "Supply Cache": "Almacén de suministros",
  "Stores delivered supplies": "Guarda suministros entregados",
  "Supply Cache: stores delivered supplies. 60 MP, 12 s": "Almacén de suministros: guarda suministros entregados. 60 MP, 12 s",
  "Logistics": "Logística",
  "Logistics overlay": "Vista logística",
  "Logistics selection": "Selección logística",
  "Resume deliveries": "Reanudar entregas",
  "Select supply trucks with a drag box": "Seleccionar camiones de suministros arrastrando un recuadro",
  "Show known supply stores and selected truck routes": "Mostrar almacenes conocidos y rutas de camiones seleccionados",
  "Right-click an allied unit or Supply Cache to deliver carried cargo": "Haz clic derecho en una unidad aliada o almacén de suministros para entregar la carga",
  "Ammunition: {0}%": "Munición: {0}%",
  "Provisions: {0} s": "Provisiones: {0} s",
  "Fuel: {0} s": "Combustible: {0} s",
  "Emergency fuel: {0} s": "Combustible de emergencia: {0} s",
  "Withdrawal in {0} s": "Retirada en {0} s",
  "Ammunition cargo: {0}": "Carga de munición: {0}",
  "Provisions cargo: {0} s": "Carga de provisiones: {0} s",
  "Fuel cargo: {0} s": "Carga de combustible: {0} s",
  "Destination: {0}, {1}": "Destino: {0}, {1}",
  "Ammunition stock: {0}/{1}": "Existencias de munición: {0}/{1}",
  "Provisions stock: {0}/{1}": "Existencias de provisiones: {0}/{1}",
  "Fuel stock: {0}/{1}": "Existencias de combustible: {0}/{1}",
  "Supply source": "Fuente de suministros",
  "Finite supply store": "Almacén de suministros limitado",
  "Ready for deliveries": "Listo para entregas",
  "Loading cargo": "Cargando suministros",
  "Unloading cargo": "Descargando suministros",
  "Delivering supplies": "Entregando suministros",
  "Returning to source": "Regresando a la fuente",
  "Deliveries held": "Entregas suspendidas",
  "Manual route": "Ruta manual",
  "Automatic deliveries": "Entregas automáticas",
  "Delivery route blocked": "Ruta de entrega bloqueada",
  "Delivery route unreachable": "Ruta de entrega inaccesible",
  "Known danger blocks deliveries": "Un peligro conocido bloquea las entregas",
  "Insufficient currency for supplies": "Recursos insuficientes para suministros",
  "Supply stockpile empty": "Existencias de suministros agotadas",
  "Mandatory withdrawal": "Retirada obligatoria",
  "Supplies in transit": "Suministros en camino",
  "Supply delivery delayed": "Entrega de suministros retrasada",
  "Stranded": "Aislado",
  "Low supplies": "Suministros escasos",
  "Supply line: {0}%": "Línea de suministro: {0}%",
  "Out of supply: refill stops in {0} s": "Sin suministro: la recarga se detiene en {0} s",
  "Cut off from supply": "Aislado del suministro",
  "Supply line restored": "Línea de suministro restablecida",
  "Show supply territory, known supply stores and selected truck routes": "Mostrar el territorio abastecido, los almacenes conocidos y las rutas de camiones seleccionados",
  "Preview unavailable": "Vista previa no disponible",
  "Choose another mode or change the scenario.": "Elige otro modo o cambia el escenario.",
  "Point": "Punto",
  // ---------- layered world and scenario authoring ----------
  "Material": "Material",
  "Automatic": "Automático",
  "Soil": "Tierra",
  "Wood": "Madera",
  "Stone": "Piedra",
  "Concrete": "Hormigón",
  "Steel": "Acero",
  "Water": "Agua",
  "Scenario events": "Eventos del escenario",
  "Add objectives and events to this map. Choose a location on the battlefield when a Pick button is active.": "Añade objetivos y eventos a este mapa. Elige una ubicación en el campo de batalla cuando un botón de selección esté activo.",
  "Edit": "Editar",
  "Areas": "Áreas",
  "Unit groups": "Grupos de unidades",
  "Objectives": "Objetivos",
  "Triggers": "Eventos",
  "Add": "Añadir",
  "Selected": "Seleccionado",
  "No entries yet.": "Todavía no hay entradas.",
  "No scenario on this map.": "Este mapa no tiene escenario.",
  "{0} areas, {1} groups, {2} objectives, {3} triggers": "{0} áreas, {1} grupos, {2} objetivos, {3} eventos",
  "Scenario JSON": "JSON del escenario",
  "For nested conditions or bulk edits. Apply checks JSON syntax before replacing the scenario.": "Para condiciones anidadas o cambios en lote. Aplicar comprueba la sintaxis JSON antes de reemplazar el escenario.",
  "Apply JSON": "Aplicar JSON",
  "ID": "ID",
  "Side": "Bando",
  "Any side": "Cualquier bando",
  "Side {0}": "Bando {0}",
  "Recipients": "Destinatarios",
  "Everyone": "Todos",
  "One side": "Un bando",
  "One team": "Un equipo",
  "Choose...": "Elegir...",
  "No area selected": "Sin área seleccionada",
  "Pick two corners": "Elegir dos esquinas",
  "Location": "Ubicación",
  "Not selected": "Sin seleccionar",
  "Pick on map": "Elegir en el mapa",
  "Pick point on map": "Elegir punto en el mapa",
  "Point {0}": "Punto {0}",
  "Region {0}": "Región {0}",
  "Seconds": "Segundos",
  "Group": "Grupo",
  "Compare": "Comparar",
  "At most": "Como máximo",
  "At least": "Como mínimo",
  "Equal": "Igual",
  "Count": "Cantidad",
  "Area": "Área",
  "Group (optional)": "Grupo (opcional)",
  "Objective": "Objetivo",
  "Trigger": "Evento",
  "Conditions JSON": "Condiciones en JSON",
  "Use condition objects from the kinds above. Each must have a kind.": "Usa objetos de condición de los tipos indicados arriba. Cada uno debe tener un campo kind.",
  "When": "Cuándo",
  "Time reached": "Se alcanza el tiempo",
  "Point owned": "Se posee un punto",
  "Unit lost": "Se pierde una unidad",
  "Group lost": "Se pierde un grupo",
  "Group count": "Cantidad del grupo",
  "Area entered": "Se entra en un área",
  "Objective complete": "Se completa un objetivo",
  "Trigger complete": "Se completa un evento",
  "All conditions": "Todas las condiciones",
  "Any condition": "Cualquier condición",
  "Message in English": "Mensaje en inglés",
  "Message in Spanish": "Mensaje en español",
  "Arrival": "Llegada",
  "Roster JSON": "Unidades de refuerzo en JSON",
  "Roster entries use a unit type and count. Example: [{\"type\":\"rifle\",\"count\":2}]": "Cada entrada indica un tipo de unidad y una cantidad. Ejemplo: [{\"type\":\"rifle\",\"count\":2}]",
  "Order": "Orden",
  "Hold": "Mantener posición",
  "Move": "Mover",
  "Attack move": "Avance de ataque",
  "Order target": "Destino de la orden",
  "Expires after seconds": "Caduca tras segundos",
  "Damage": "Daño",
  "Action {0}": "Acción {0}",
  "Remove": "Quitar",
  "Do": "Hacer",
  "Show message": "Mostrar mensaje",
  "Activate objective": "Activar objetivo",
  "Complete objective": "Completar objetivo",
  "Send reinforcements": "Enviar refuerzos",
  "Damage area": "Dañar área",
  "Destroy area": "Destruir área",
  "Add unit": "Añadir unidad",
  "Unit {0}": "Unidad {0}",
  "Cell": "Casilla",
  "English": "Inglés",
  "Scope": "Ámbito",
  "Whole match": "Toda la partida",
  "Each player": "Cada jugador",
  "Each team": "Cada equipo",
  "Repeat": "Repetir",
  "Once": "Una vez",
  "When it becomes true": "Cuando se cumple",
  "While true": "Mientras se cumple",
  "Cooldown seconds": "Segundos entre ejecuciones",
  "Maximum runs": "Máximo de ejecuciones",
  "Actions": "Acciones",
  "Add action": "Añadir acción",
  "Remove area": "Quitar área",
  "Remove group": "Quitar grupo",
  "Remove objective": "Quitar objetivo",
  "Remove trigger": "Quitar evento",
  "Click two corners. Esc cancels.": "Haz clic en dos esquinas. Esc cancela.",
  "Click a cell or point. Esc cancels.": "Haz clic en una casilla o punto. Esc cancela.",
  "Click a capture point.": "Haz clic en un punto de captura.",
  "Click the opposite corner.": "Haz clic en la esquina opuesta.",
  "Selection cancelled.": "Selección cancelada.",
  "Expected version 1 with areas, groups, objectives and triggers lists.": "Se esperaba la versión 1 con listas de áreas, grupos, objetivos y eventos.",
  "Every entry needs an ID and its required lists.": "Cada entrada necesita un ID y sus listas obligatorias.",
  "JSON not applied: {0}": "JSON sin aplicar: {0}",
  "JSON syntax is invalid. Check commas, brackets and quotation marks.": "La sintaxis JSON no es válida. Revisa las comas, los corchetes y las comillas.",
  "Use a unique ID with letters, numbers, colons, underscores or dashes.": "Usa un ID único con letras, números, dos puntos, guiones bajos o guiones.",
  "Check the scenario data.": "Revisa los datos del escenario.",
  "Wrong password.": "Contraseña incorrecta.",
  "Map not opened ({0}).": "No se abrió el mapa ({0}).",
  "Authoring source opened.": "Se abrió el mapa completo.",
  "Public preview. Enter the password and click Open before saving.": "Vista pública. Escribe la contraseña y pulsa Abrir antes de guardar.",
  "Map not opened. Check the connection.": "No se abrió el mapa. Comprueba la conexión.",
  "Open the complete map with the password before saving.": "Abre el mapa completo con la contraseña antes de guardar.",
  "The whole object must fit inside the map without overlapping another object.": "El objeto completo debe caber en el mapa sin superponerse a otro objeto.",
  "{0} tool: click or drag to paint the base surface, right-drag erases mines, then objects, then ground": "Herramienta {0}: haz clic o arrastra para pintar el terreno base; arrastrar con el botón derecho borra minas, luego objetos y luego terreno",
  "{0} tool: click or drag to paint an object above the surface, right-drag erases mines, then objects, then ground": "Herramienta {0}: haz clic o arrastra para pintar un objeto sobre el terreno; arrastrar con el botón derecho borra minas, luego objetos y luego terreno",
  "Mines use their own layer. Laying or clearing them preserves the surface and rubble underneath.": "Las minas usan su propia capa. Colocarlas o retirarlas conserva el terreno y los escombros de debajo.",
  "Preview unavailable: {0}. Choose another mode or change the scenario.": "Vista previa no disponible: {0}. Elige otro modo o cambia el escenario.",
  "Support section IDs for {0}": "IDs de las secciones que apoyan a {0}",
  "Structural sections": "Secciones estructurales",
  "Structure ID": "ID de estructura",
  "Section / cell": "Sección / casilla",
  "Health": "Salud",
  "Anchor": "Anclaje",
  "Supports": "Apoyos",
  "Apply sections": "Aplicar secciones",
  "Use inferred support": "Usar apoyos automáticos",
  "Select up to 128 house or bridge cells to edit support.": "Selecciona hasta 128 casillas de casa o puente para editar sus apoyos.",
  "Each section needs a path to a surviving anchor. Bridge anchors attach to a bank. Supports use adjacent section IDs.": "Cada sección necesita una cadena de apoyos hasta un anclaje que siga en pie. Los anclajes del puente tocan una orilla. Los apoyos usan IDs de secciones vecinas.",

  'That recruit is no longer waiting': 'Ese recluta ya no está en espera',
  'This scenario cannot start with the selected sides, factions or mode': 'Este escenario no puede empezar con los bandos, facciones o modo seleccionados',
  'Training: {0}': 'Entrenando: {0}',
  'Waiting: {0}': 'En espera: {0}',
  'Cancel: refund {0} MP, {1} Fuel': 'Cancelar: devolver {0} MP, {1} combustible',
  'Cancel {0}: refund {1} MP, {2} Fuel': 'Cancelar {0}: devolver {1} MP, {2} combustible',
  'Alert history': 'Historial de alertas',
  'Open or close Alert history': 'Abrir o cerrar el historial de alertas',
  'Open or close Alert history (Alt+H)': 'Abrir o cerrar el historial de alertas (Alt+H)',
  'Previous Alert': 'Alerta anterior',
  'Next Alert': 'Alerta siguiente',
  'No Alerts yet': 'Todavía no hay alertas',
  'Alert at {0}: {1}': 'Alerta a las {0}: {1}',
  'No recorded location': 'Sin ubicación registrada',
  'Recorded location: {0}, {1}': 'Ubicación registrada: {0}, {1}',
  'Visit the previous Alert': 'Ver la alerta anterior',
  'Visit the next Alert': 'Ver la alerta siguiente',
  'Visit the previous or next Alert at its recorded location': 'Ver la alerta anterior o siguiente en su ubicación registrada',
  'Control group': 'Grupo de control',
  'Destination control group': 'Grupo de control de destino',
  'Move to group': 'Mover al grupo',
  'Move selected units to a control group and remove them from other groups': 'Mover las unidades seleccionadas a un grupo de control y quitarlas de los demás grupos',
  'Move selected units to group {0} and remove them from other groups': 'Mover las unidades seleccionadas al grupo {0} y quitarlas de los demás grupos',
  'Alt+1 to Alt+9 moves selected units and removes them from other groups': 'Alt+1 a Alt+9 mueve las unidades seleccionadas y las quita de los demás grupos',
  'Moved {0} units to group {1}; removed from other groups': 'Se movieron {0} unidades al grupo {1}; se quitaron de los demás grupos',
  'Next Wave: {0}': 'Próxima oleada: {0}',
  'Mixed forces': 'Fuerzas mixtas',
  'Infantry assault': 'Asalto de infantería',
  'Armored assault': 'Asalto blindado',
  'Siege weapons': 'Armas de asedio',

  // ---------- lobby (index.html, main.js) ----------
  'Browse matches': 'Ver partidas',
  'Players': 'Jugadores',
  'Name': 'Nombre',
  'Language': 'Idioma',
  '+ Add AI player': '+ Añadir jugador IA',
  'Fill an open slot with an AI player': 'Ocupa un puesto libre con un jugador IA',
  'Spectators see the whole map and command nothing. With only AI players seated, a spectator hosts': 'Los espectadores ven todo el mapa y no controlan nada. Si solo hay jugadores IA sentados, un espectador hace de anfitrión',
  'Invite': 'Invitar',
  'Send this link to friends. It always opens this room.': 'Envía este enlace a tus amigos. Siempre abre esta sala.',
  'Copy': 'Copiar',
  'Copy the invite link': 'Copia el enlace de invitación',
  'Copied': 'Copiado',
  'Clipboard unavailable': 'Portapapeles no disponible',
  'Press Ctrl+C': 'Pulsa Ctrl+C',
  'Room': 'Sala',
  'Join': 'Unirse',
  'New': 'Nueva',
  'Type a room code and press Join; leave it as main for the usual room': 'Escribe un código de sala y pulsa Unirse; deja main para la sala habitual',
  'Join the room code typed on the left': 'Unirse a la sala escrita a la izquierda',
  'A private room with a random code': 'Una sala privada con un código aleatorio',
  'Battle': 'Batalla',
  'Map': 'Mapa',
  'Mode': 'Modo',
  'Conquest': 'Conquista',
  'Assault': 'Asalto',
  'Annihilation': 'Aniquilación',
  'Classic': 'Clásico',
  'Horde': 'Horda',
  'Army size': 'Tamaño del ejército',
  'Unit limit and income for everyone': 'Límite de unidades e ingresos para todos',
  'Standard': 'Estándar',
  'Large: 2.5x units, 3x income': 'Grande: 2,5x unidades, 3x ingresos',
  'Massive: 5x units, 6x income': 'Masivo: 5x unidades, 6x ingresos',
  'Endless: 5x units, 20x income': 'Infinito: 5x unidades, 20x ingresos',
  '{0}: {1}x units, {2}x income': '{0}: {1}x unidades, {2}x ingresos',
  'Large': 'Grande',
  'Massive': 'Masivo',
  'Endless': 'Infinito',
  'Weather': 'Clima',
  'Start': 'Empezar',
  'Play again': 'Jugar otra vez',
  'Start the match for everyone in the room': 'Empieza la partida para todos los de la sala',
  'Start: {0}': 'Empezar: {0}',
  'Play again: {0}': 'Jugar otra vez: {0}',
  'solo test': 'prueba en solitario',
  'co-op': 'cooperativo',
  'assault': 'asalto',
  '{0}-way FFA': 'todos contra todos ({0})',
  'classic {0}': 'clásico {0}',
  'annihilation {0}': 'aniquilación {0}',
  'horde, 1 defender': 'horda, 1 defensor',
  'horde, {0} defenders': 'horda, {0} defensores',
  'Map editor': 'Editor de mapas',
  'Open in another tab': 'Abierto en otra pestaña',
  'Use it here': 'Usarlo aquí',
  'USA': 'EE. UU.',
  'Germany': 'Alemania',
  'USSR': 'URSS',
  'UK': 'Reino Unido',
  'Easy': 'Fácil',
  'Normal': 'Normal',
  'Hard': 'Difícil',
  'AI difficulty': 'Dificultad de la IA',
  'Team {0}': 'Equipo {0}',
  'Team {0} defends ({1})': 'El equipo {0} defiende ({1})',
  'Remove AI': 'Quitar IA',
  'Remove offline player': 'Quitar jugador desconectado',
  'open slot': 'puesto libre',
  'Watching: {0}': 'Observando: {0}',
  'Take a seat': 'Ocupar un puesto',
  'Watch as a spectator': 'Mirar como espectador',
  'you, host': 'tú, anfitrión',
  'you': 'tú',
  'host': 'anfitrión',
  'offline': 'desconectado',
  'AI': 'IA',
  'AI {0}': 'IA {0}',
  '{0} (AI)': '{0} (IA)',
  'Capture and hold points to earn victory points. First side to the VP goal wins.': 'Captura y mantén puntos para ganar puntos de victoria. Gana el primer bando que llega a la meta de PV.',
  'One team defends a fortified command bunker. Everyone else attacks and must destroy it before the clock runs out.': 'Un equipo defiende un búnker de mando fortificado. Todos los demás atacan y deben destruirlo antes de que se acabe el tiempo.',
  'Every side starts with a fortified command bunker. Destroy every enemy bunker: last side standing wins. No clock.': 'Cada bando empieza con un búnker de mando fortificado. Destruye todos los búnkeres enemigos: gana el último bando en pie. Sin reloj.',
  'Build a base with engineers and train an army. Destroy every enemy HQ, Barracks, Motor Pool and Airfield.': 'Construye una base con ingenieros y entrena un ejército. Destruye todos los CG, Cuarteles, Parques móviles y Aeródromos enemigos.',
  'Co-op: everyone shares one HQ and defends one command bunker against waves that keep growing. The next wave comes when the last one is dead. How far can you get?': 'Cooperativo: todos comparten un CG y defienden un búnker de mando contra oleadas cada vez mayores. La siguiente oleada llega cuando muere la anterior. ¿Hasta dónde llegarás?',
  'up to {0} defenders': 'hasta {0} defensores',
  'up to {0} players': 'hasta {0} jugadores',
  '1 capture point': '1 punto de captura',
  '{0} capture points': '{0} puntos de captura',
  'hills and cliffs': 'colinas y acantilados',
  'rolling hills': 'colinas suaves',
  'rivers': 'ríos',
  'your HQ is one of these,': 'tu CG es uno de estos,',
  'the horde comes from here': 'la horda viene de aquí',
  'defend,': 'defensa,',
  'attack': 'ataque',
  'built for Assault': 'hecho para Asalto',
  '{0} minute clock': 'reloj de {0} minutos',
  'Horde seats {0} defenders: remove a player.': 'La Horda admite {0} defensores: quita un jugador.',
  'This map has {0} spawns: pick a bigger map or remove players.': 'Este mapa tiene {0} puntos de inicio: elige un mapa más grande o quita jugadores.',
  'Assault needs players on the defending team and on another team.': 'Asalto necesita jugadores en el equipo defensor y en otro equipo.',
  'Send the invite link, or add an AI {0}.': 'Envía el enlace de invitación o añade una IA {0}.',
  'Send the invite link, or add an AI player.': 'Envía el enlace de invitación o añade un jugador IA.',
  'Send the invite link, or add an AI opponent.': 'Envía el enlace de invitación o añade un rival IA.',
  'Waiting for the host to start...': 'Esperando a que el anfitrión empiece...',
  'Match ended by the host': 'El anfitrión terminó la partida',
  'Overrun on wave {0}: {1} kills in {2}{3}': 'Arrollados en la oleada {0}: {1} bajas causadas en {2}{3}',
  ', a new record': ', nuevo récord',
  '. Record: wave {0}': '. Récord: oleada {0}',
  '{0} wins': 'Victoria de {0}',
  '{0} win': 'Victoria de {0}',
  'Enemy': 'Enemigo',
  'Trying this room again in {0} s': 'Reintentando esta sala en {0} s',
  'Connection lost. Retrying in {0} s': 'Conexión perdida. Reintentando en {0} s',
  'The server cannot create more rooms right now. Browse matches to join an existing room, or wait for a retry.': 'El servidor no puede crear más salas ahora. Busca una partida para unirte a una sala existente o espera un reintento.',
  'A match is running in this room. You will join when it ends.': 'Hay una partida en curso en esta sala. Entrarás cuando termine.',
  'This room is full. You will join when a seat opens.': 'Esta sala está llena. Entrarás cuando quede un puesto libre.',
  'You left the match; an AI took over your army. Reload to rejoin the lobby when the match is over.': 'Saliste de la partida; una IA tomó tu ejército. Recarga para volver a la sala cuando termine la partida.',
  'Match started': 'Partida iniciada',
  'the host': 'el anfitrión',
  'Waiting for {0} ({1} s)': 'Esperando a {0} ({1} s)',
  'Paused by {0}': 'Pausada por {0}',
  'Paused by the host': 'Pausada por el anfitrión',

  // ---------- the in-game menu and top bar ----------
  'Menu': 'Menú',
  'Menu: restart, end or leave the match': 'Menú: reiniciar, terminar o abandonar la partida',
  'Fullscreen': 'Pantalla completa',
  'Fullscreen: also lets Ctrl+1-9 set groups': 'Pantalla completa: además permite que Ctrl+1-9 asigne grupos',
  'Capture mouse': 'Capturar ratón',
  'Capture mouse: keeps the cursor inside the game so edge scrolling always works. Click again or press Esc to let go': 'Capturar ratón: mantiene el cursor dentro del juego para que el desplazamiento por los bordes siempre funcione. Vuelve a hacer clic o pulsa Esc para soltarlo',
  'Controls and mouse help (F1)': 'Controles y ayuda del ratón (F1)',
  'Controls, F1': 'Controles, F1',
  'Pause match': 'Pausar partida',
  'Resume match': 'Reanudar partida',
  'Restart match': 'Reiniciar partida',
  'End match (back to lobby)': 'Terminar partida (volver a la sala)',
  'Leave game': 'Abandonar juego',
  'Click again to confirm': 'Haz clic otra vez para confirmar',
  'Hand {0} to AI': 'Pasar a {0} a la IA',
  'Edge scroll: On': 'Desplazamiento por bordes: Sí',
  'Edge scroll: Off': 'Desplazamiento por bordes: No',
  'Edge scroll: {0}': 'Desplazamiento por bordes: {0}',
  'Capture mouse: {0}': 'Capturar ratón: {0}',
  'In fullscreen': 'En pantalla completa',
  'Always': 'Siempre',
  'Never': 'Nunca',
  'Keep the cursor inside the game while you play, so pushing past the screen edge always scrolls. Esc lets go': 'Mantiene el cursor dentro del juego mientras juegas, así empujar más allá del borde siempre desplaza. Esc lo suelta',
  'Pan speed: {0}': 'Velocidad de desplazamiento: {0}',
  'Slow': 'Lenta',
  'Fast': 'Rápida',
  'Very fast': 'Muy rápida',
  'Stats overlay: {0}': 'Panel de estadísticas: {0}',
  'Frame rate, ping, loss and other numbers over the game (F2 shows or hides)': 'Fotogramas, ping, pérdida y otros números sobre el juego (F2 muestra u oculta)',
  'Volume': 'Volumen',
  'Low uses cheaper shadows, fewer particles and no cloud shadows or birds': 'Bajos usa sombras más baratas, menos partículas y sin sombras de nubes ni pájaros',
  'Blood and torn bodies when men die in a blast': 'Sangre y cuerpos destrozados cuando los soldados mueren en una explosión',
  'Cover preview: {0}': 'Vista de cobertura: {0}',
  'Cover preview': 'Vista de cobertura',
  'With infantry selected, mark the cover around the cursor': 'Con infantería seleccionada, marca la cobertura alrededor del cursor',
  'green heavy, yellow light, red open': 'verde pesada, amarillo ligera, rojo al descubierto',
  'Graphics: Low': 'Gráficos: Bajos',
  'Graphics: High': 'Gráficos: Altos',
  'Gore: {0}': 'Sangre: {0}',
  'Graphics set to Low to keep the game smooth. Change it in the menu.': 'Gráficos en Bajos para que el juego vaya fluido. Cámbialo en el menú.',
  'Effects, voices and alerts. M mutes': 'Efectos, voces y alertas. M silencia',
  'On': 'Sí',
  'Off': 'No',
  'MP': 'MO',
  'Mun': 'Mun',
  'Fuel': 'Comb',
  'Manpower: buys units, fortifications and support': 'Mano de obra: compra unidades, fortificaciones y apoyo',
  'Munitions: support calls and abilities. Hold points to earn them': 'Munición: llamadas de apoyo y habilidades. Mantén puntos para ganarla',
  'Fuel: vehicles. Depots on the contested nodes and the HQ earn it': 'Combustible: vehículos. Lo ganan los depósitos en los nodos disputados y el CG',
  'Income per second': 'Ingresos por segundo',
  'Army size: units fielded and in training, out of the cap': 'Tamaño del ejército: unidades en el campo y en entrenamiento, sobre el límite',
  '{0}/{1} units': '{0}/{1} unidades',
  '+{0} MP/s': '+{0} MO/s',
  '+{0} Mun/s': '+{0} Mun/s',
  '+{0} Fuel/s': '+{0} Comb/s',
  '{0} MP': '{0} MO',
  '{0} Mun': '{0} Mun',
  '{0} Fuel': '{0} Comb',
  '{0} Fuel,': '{0} Comb,',
  '{0} MP/s': '{0} MO/s',
  'MP/s': 'MO/s',
  'Offline': 'Desconectado',
  '{0} ms': '{0} ms',
  'Offline: the clock is paused until they return': 'Desconectado: el reloj está en pausa hasta que vuelva',
  'Wave {0}': 'Oleada {0}',
  'Wave {0} in': 'Oleada {0} en',
  '{0} left': 'quedan {0}',
  'Next wave': 'Siguiente oleada',
  'Send the next wave now': 'Enviar ya la siguiente oleada',
  'Hold the bunker. The next wave comes 45 seconds after this one is dead': 'Defiende el búnker. La siguiente oleada llega 45 segundos después de acabar con esta',
  'Assault: hold out': 'Asalto: resiste',
  'Assault: take the bunker': 'Asalto: toma el búnker',
  'Hold out until the clock runs out': 'Resiste hasta que se acabe el tiempo',
  'Destroy the command bunker before the clock runs out': 'Destruye el búnker de mando antes de que se acabe el tiempo',
  'Sudden death': 'Muerte súbita',
  'Sudden death in': 'Muerte súbita en',
  'Sudden Death': 'Muerte súbita',
  'No building or training. Bases crumble: last one standing wins': 'Sin construir ni entrenar. Las bases se derrumban: gana el último en pie',
  'Destroy every enemy HQ, Barracks, Motor Pool and Airfield': 'Destruye todos los CG, Cuarteles, Parques móviles y Aeródromos enemigos',
  'Destroy every enemy bunker. Last side standing wins': 'Destruye todos los búnkeres enemigos. Gana el último bando en pie',
  'First to {0} VP': 'Primero a {0} PV',
  'first to {0} VP': 'primero a {0} PV',
  '{0} VP': '{0} PV',
  'VP': 'PV',
  '{0} pts, {1} held': '{0} pts, {1} en poder',
  '{0} held': '{0} en poder',
  'Out': 'Eliminado',
  'Defending': 'Defiende',
  'Attacking': 'Ataca',
  'Structures left': 'Estructuras restantes',
  'Bunker': 'Búnker',
  'Bunker lost': 'Búnker perdido',
  '1 bunker': '1 búnker',
  '{0} bunkers': '{0} búnkeres',
  'HQ out of sight': 'CG fuera de la vista',
  'YOU': 'TÚ',
  'You': 'Tú',

  // ---------- the controls sheet (F1) ----------
  'Controls': 'Controles',
  'Close': 'Cerrar',
  'Close controls': 'Cerrar controles',
  'Mouse': 'Ratón',
  'Left click': 'Clic izquierdo',
  'Select a unit or building': 'Selecciona una unidad o edificio',
  'Drag': 'Arrastrar',
  'Select units in a box': 'Selecciona unidades dentro de un recuadro',
  'Shift + click / drag': 'Shift + clic / arrastrar',
  'Add to or remove from your selection': 'Añade o quita de tu selección',
  'Double-click': 'Doble clic',
  'Select nearby units of the same type; Ctrl/Command includes the whole map': 'Selecciona las unidades cercanas del mismo tipo; con Ctrl/Comando, las de todo el mapa',
  'Right-click': 'Clic derecho',
  'Move, attack, garrison, or interact with the target': 'Mover, atacar, guarnecer o interactuar con el objetivo',
  'Shift + right-click': 'Shift + clic derecho',
  'Queue the order': 'Encola la orden',
  'Ctrl + right-click': 'Ctrl + clic derecho',
  'Attack-move, fighting anything met along the way': 'Avance de ataque: combate todo lo que encuentre por el camino',
  'Right-click-drag': 'Arrastrar con clic derecho',
  'Set a destination and facing for the formation; release to confirm': 'Fija destino y orientación de la formación; suelta para confirmar',
  'Wheel': 'Rueda',
  'Zoom at the cursor': 'Zoom hacia el cursor',
  'Middle-drag': 'Arrastrar con clic central',
  'Rotate the camera': 'Gira la cámara',
  'Map edge': 'Borde del mapa',
  'Move the cursor to an edge to scroll': 'Lleva el cursor a un borde para desplazarte',
  'Minimap': 'Minimapa',
  'Left-drag to move the camera; right-click to order': 'Arrastra con clic izquierdo para mover la cámara; clic derecho para dar órdenes',
  'Alt + left-click': 'Alt + clic izquierdo',
  'Ping a spot for your team': 'Marca un punto para tu equipo',
  'While aiming': 'Al apuntar',
  'Click to place or call in; move to aim direction. Right-click cancels': 'Clic para colocar o pedir; mueve para orientar. Clic derecho cancela',
  'Camera': 'Cámara',
  '/ arrows': '/ flechas',
  'Pan': 'Desplazar',
  'Rotate left / right': 'Girar a la izquierda / derecha',
  'Open or close this sheet': 'Abre o cierra esta hoja',
  'Show or hide the stats overlay (pick the numbers in the menu)': 'Muestra u oculta el panel de estadísticas (elige los números en el menú)',
  'Mute or unmute audio': 'Silencia o activa el audio',
  'Units and orders': 'Unidades y órdenes',
  'Stop / retreat selected units': 'Detener / retirar las unidades seleccionadas',
  'Use a ready ability / aim attack-move': 'Usar una habilidad lista / apuntar avance de ataque',
  'Unload the selected halftrack': 'Descarga el semioruga seleccionado',
  'Take cover': 'Ponerse a cubierto',
  'Toggle hold fire, hold position, auto-retreat': 'Activa alto el fuego, mantener posición, retirada automática',
  'Select your whole army': 'Selecciona todo tu ejército',
  'Select next idle unit / all idle units': 'Selecciona la siguiente unidad ociosa / todas las ociosas',
  'Select the next idle Engineer': 'Selecciona el siguiente Ingeniero ocioso',
  'Space': 'Espacio',
  'Shift+Space': 'Shift+Espacio',
  'Jump to newest alert or selection / follow selection': 'Salta a la última alerta o a la selección / seguir la selección',
  'Recall a control group; tap twice to center': 'Recupera un grupo de control; pulsa dos veces para centrar',
  'Set a control group; Shift adds to it': 'Asigna un grupo de control; Shift añade a él',
  'Go home in Classic / set army rally point': 'Volver a la base en Clásico / fijar el punto de reunión del ejército',
  'Clear selection, cancel aiming, or release captured mouse': 'Borra la selección, cancela la puntería o suelta el ratón capturado',
  'Recruiting and building': 'Reclutar y construir',
  'Turn recruit letters on or off': 'Activa o desactiva las letras de reclutamiento',
  'Choose a card while recruiting; Shift + letter buys up to five': 'Elige una carta al reclutar; Shift + letra compra hasta cinco',
  'Place Depot, Barracks, Motorpool, Airfield, Flak position in Classic': 'Coloca Depósito, Cuartel, Parque móvil, Aeródromo y posición antiaérea en Clásico',
  'Place a trench / dig a trench line': 'Coloca una trinchera / cava una línea de trinchera',
  'Place sandbags, wire, traps, nest, mines, bridge, fill ground, or demine': 'Coloca sacos terreros, alambre, obstáculos, nido, minas, puente, rellenar terreno o desminar',
  'Build from a builder squad\'s orders panel': 'Se construye desde el panel de órdenes de un pelotón constructor',
  'Support keys': 'Teclas de apoyo',
  'Recon,': 'Reconocimiento,',
  'Artillery,': 'Artillería,',
  'Strafe,': 'Ametrallamiento,',
  'Smoke,': 'Humo,',
  'Bombing,': 'Bombardeo,',
  'Dive,': 'Picado,',
  'Paratroops,': 'Paracaidistas,',
  'Air cover': 'Cobertura aérea',

  // ---------- stats overlay (index.html, stats.js) ----------
  'Stats overlay': 'Panel de estadísticas',
  'Close stats overlay settings': 'Cerrar ajustes del panel de estadísticas',
  'Show the overlay': 'Mostrar el panel',
  'Quick pick': 'Elección rápida',
  'Look': 'Aspecto',
  'Position': 'Posición',
  'Layout': 'Disposición',
  'Size': 'Tamaño',
  'Background': 'Fondo',
  'Color warnings: amber, then red, when a number is bad': 'Avisos de color: ámbar y luego rojo cuando un número es malo',
  'Performance': 'Rendimiento',
  'Frame rate': 'Fotogramas por segundo',
  'Frame': 'Fotograma',
  'Frame time': 'Tiempo de fotograma',
  'Average over the last second': 'Media del último segundo',
  'Worst': 'Peor',
  'Worst frame': 'Peor fotograma',
  'Longest in the last second: hitches': 'El más largo del último segundo: tirones',
  'Script time': 'Tiempo de script',
  'Game code per frame': 'Código del juego por fotograma',
  'Draws': 'Dibujos',
  'Draw calls': 'Llamadas de dibujo',
  'Tris': 'Tris',
  'Triangles': 'Triángulos',
  'Res': 'Res',
  'Render scale and graphics': 'Escala de render y gráficos',
  'Mem': 'Mem',
  'Memory': 'Memoria',
  'Chrome and Edge only': 'Solo Chrome y Edge',
  'Network': 'Red',
  'Ping': 'Ping',
  'Round trip to the server': 'Ida y vuelta al servidor',
  'Jitter': 'Variación',
  'How much the ping swings': 'Cuánto oscila el ping',
  'Loss': 'Pérdida',
  'Pings unanswered after 3 s, last minute': 'Pings sin respuesta tras 3 s, último minuto',
  'Upd': 'Act',
  'Updates per second': 'Actualizaciones por segundo',
  'Game state messages received': 'Mensajes de estado del juego recibidos',
  'Gap': 'Hueco',
  'Longest update gap': 'Mayor hueco entre actualizaciones',
  'Longest wait in the last second: stalls': 'Espera más larga del último segundo: parones',
  'Update size': 'Tamaño de actualización',
  'Download rate': 'Velocidad de descarga',
  'Server': 'Servidor',
  'Server tick': 'Tick del servidor',
  'Slowest 5% of ticks that send an update; over 40 ms it sends fewer': 'El 5% más lento de los ticks que envían actualización; por encima de 40 ms envía menos',
  'Game': 'Juego',
  'Units': 'Unidades',
  'Effect particles': 'Partículas de efectos',
  'Bodies': 'Cuerpos',
  'Top left': 'Arriba a la izquierda',
  'Top center': 'Arriba al centro',
  'Top right': 'Arriba a la derecha',
  'List': 'Lista',
  'One line': 'Una línea',
  'Small': 'Pequeño',
  'Medium': 'Mediano',
  'Panel': 'Panel',
  'None': 'Ninguno',
  'Everything': 'Todo',
  'See-through': 'Transparente',
  'No stats picked. Menu > Stats overlay': 'No hay estadísticas elegidas. Menú > Panel de estadísticas',
  'Basic': 'Básico',
  'Full': 'Completo',
  'Lag': 'Lag',

  // ---------- alerts, status lines, endgame ----------
  'Space or click: look there': 'Espacio o clic: mirar allí',
  'Allied': 'Aliado',
  '{0} under attack': '{0} bajo ataque',
  'Units under attack': 'Unidades bajo ataque',
  'Point lost': 'Punto perdido',
  'Point captured': 'Punto capturado',
  '{0} captured a point': '{0} capturó un punto',
  'Point under attack': 'Punto bajo ataque',
  'Point cut off: it pays nothing until the road to it is open': 'Punto aislado: no produce nada hasta que se abra el camino hasta él',
  '{0} units lost': '{0} unidades perdidas',
  '{0} destroyed': 'Destruido: {0}',
  '{0} lost': 'Perdido: {0}',
  'Enemy {0} incoming': 'Llega enemigo: {0}',
  '{0} ready': 'Listo: {0}',
  '{0} finished': 'Terminado: {0}',
  'Ping from {0}': 'Marca de {0}',
  'Blue': 'Azul',
  'Red': 'Rojo',
  'Chalk': 'Tiza',
  'Orange': 'Naranja',
  'Violet': 'Violeta',
  'Cyan': 'Cian',
  'Spectating: the whole map is in view': 'Espectador: todo el mapa a la vista',
  'You are out. Watching with your team\'s vision': 'Estás eliminado. Observas con la visión de tu equipo',
  '{0} takes the lead': '{0} toma la delantera',
  '{0} leads, victory is over an hour away at this rate': '{0} va por delante; a este ritmo la victoria está a más de una hora',
  '{0} wins in {1} at this rate': 'A este ritmo, {0} gana en {1}',
  '{0} leads. {1}': '{0} va por delante. {1}',
  'Measuring victory rate': 'Midiendo el ritmo de victoria',
  'No VP gain at this rate': 'Sin ganancia de PV a este ritmo',
  'Tutorial': 'Tutorial',
  'Scores tied': 'Empate en el marcador',
  '{0} catch-up +{1} MP/s each': '{0} recuperación +{1} MO/s cada uno',
  'Wave {0} incoming': 'Llega la oleada {0}',
  'Wave {0} cleared. The bunker is patched up': 'Oleada {0} superada. El búnker queda reparado',
  'The last of the wave are marked through the fog': 'Los últimos de la oleada se marcan a través de la niebla',
  'Assault ends in {0}': 'El asalto termina en {0}',
  'Sudden Death begins. Production has stopped': 'Empieza la muerte súbita. La producción se ha detenido',
  'Sudden Death: Production Buildings are crumbling': 'Muerte súbita: los edificios de producción se derrumban',
  'Victory': 'Victoria',
  'Defeat': 'Derrota',
  'Draw': 'Empate',
  'Your side reached the victory points first.': 'Tu bando llegó primero a los puntos de victoria.',
  'The enemy reached the victory points first.': 'El enemigo llegó primero a los puntos de victoria.',
  'Your bunkers are the last ones standing.': 'Tus búnkeres son los últimos en pie.',
  'The enemy\'s bunkers are the last ones standing.': 'Los búnkeres enemigos son los últimos en pie.',
  'Every defending structure has fallen.': 'Ha caído toda estructura defensora.',
  'Every structure you defended has fallen.': 'Ha caído toda estructura que defendías.',
  'The defenses held until the clock ran out.': 'Las defensas aguantaron hasta que se acabó el tiempo.',
  'The clock ran out before the defenses fell.': 'Se acabó el tiempo antes de que cayeran las defensas.',
  'Your side has the last Production Buildings standing.': 'Tu bando tiene los últimos edificios de producción en pie.',
  'The enemy has the last Production Buildings standing.': 'El enemigo tiene los últimos edificios de producción en pie.',
  'No side is left standing.': 'No queda ningún bando en pie.',
  'The bunker fell on wave {0}.': 'El búnker cayó en la oleada {0}.',
  'The {0} has collapsed': 'Se ha derrumbado: {0}',
  '{0} {1} has collapsed': 'Se ha derrumbado: {1} ({0})',
  'Your': 'tuyo',
  'The allied': 'aliado',
  'The enemy': 'enemigo',
  'An ally': 'Un aliado',
  // map triggers (The Great Bridge)
  'Enemy engineers are wiring the great bridge. It goes up at 7:00.': 'Ingenieros enemigos están minando el gran puente. Vuela a las 7:00.',
  'Twenty seconds: get off the great bridge!': 'Veinte segundos: ¡salid del gran puente!',
  'The great bridge is down. The way over now is the ford to the north or the rail bridge to the south.': 'El gran puente ha caído. Ahora se cruza por el vado del norte o por el puente del ferrocarril del sur.',

  // ---------- match report (report.js) ----------
  'Match report': 'Informe de la partida',
  'Player': 'Jugador',
  'Player {0}': 'Jugador {0}',
  'Kills': 'Bajas causadas',
  'Losses': 'Pérdidas',
  'Built': 'Construido',
  'Captures': 'Capturas',
  'Manpower spent': 'Mano de obra gastada',
  'Support calls': 'Llamadas de apoyo',
  'Planes downed': 'Aviones derribados',
  'Victory points': 'Puntos de victoria',
  'Points held': 'Puntos en poder',
  '{0} victory points': '{0} puntos de victoria',
  '{0} points held': '{0} puntos en poder',
  '{0} over time for each side': '{0} a lo largo del tiempo para cada bando',
  '{0} over time': '{0} a lo largo del tiempo',
  'on victory points': 'por puntos de victoria',
  'when the last bunker fell': 'al caer el último búnker',
  'when the last defending structure fell': 'al caer la última estructura defensora',
  'when the clock ran out': 'al acabarse el tiempo',
  'when the last Production Building fell': 'al caer el último edificio de producción',
  'in a draw': 'en empate',
  'Decided {0} after {1}': 'Decidida {0} tras {1}',
  'Ended {0} after {1}': 'Terminada {0} tras {1}',
  'Structures': 'Estructuras',

  // ---------- availability (why a button is greyed) ----------
  'Not enough manpower': 'No hay suficiente mano de obra',
  'Not enough munitions': 'No hay suficiente munición',
  'Not enough fuel': 'No hay suficiente combustible',
  'The army is at its limit': 'El ejército está en su límite',
  'That order is still on cooldown': 'Esa orden todavía se está recargando',
  'That target is not visible': 'Ese objetivo no está a la vista',
  'That spot is not visible': 'Ese lugar no está a la vista',
  'That spot is blocked or uneven': 'Ese lugar está bloqueado o es irregular',
  'The required unit or building is missing': 'Falta la unidad o el edificio necesario',
  'That unit or position is at its limit': 'Esa unidad o posición está en su límite',
  'Not during Sudden Death': 'No durante la muerte súbita',
  'The training queue is full': 'La cola de entrenamiento está llena',
  'This unit already has 8 queued orders': 'Esta unidad ya tiene 8 órdenes en cola',
  'That squad is retreating': 'Ese pelotón se está retirando',
  'Select a builder squad': 'Selecciona un pelotón constructor',
  'No cover within reach': 'No hay cobertura a su alcance',
  'A Shipyard needs open water beside it': 'Un Astillero necesita agua abierta al lado',
  'Too far from the shore to land': 'Demasiado lejos de la orilla para desembarcar',
  'That order cannot happen': 'Esa orden no puede cumplirse',
  'Needs {0} MP': 'Necesita {0} MO',
  'Needs {0} fuel': 'Necesita {0} de combustible',
  'Needs {0} munitions': 'Necesita {0} de munición',
  'Waiting for the army': 'Esperando al ejército',
  'Army at its limit ({0}/{1})': 'Ejército en su límite ({0}/{1})',
  'Unavailable in this mode': 'No disponible en este modo',
  'Needs a map with a sea': 'Necesita un mapa con mar',
  'Maximum of this unit reached': 'Máximo de esta unidad alcanzado',
  'Needs a {0}': 'Necesita: {0}',
  'Cooldown {0} s': 'Recarga {0} s',
  'Select a unit': 'Selecciona una unidad',
  'Select an infantry squad': 'Selecciona un pelotón de infantería',
  'Select a squad': 'Selecciona un pelotón',

  // ---------- HUD: support calls, fortifications, stances ----------
  'Reveals a wide area for 15s': 'Revela una zona amplia durante 15 s',
  '10 shells on an area after a 5s warning (UK: 15, the 25-pounder doctrine)': '10 proyectiles sobre una zona tras un aviso de 5 s (Reino Unido: 15, la doctrina del 25 libras)',
  'Plane rakes a line from your HQ outward': 'Un avión barre una línea desde tu CG hacia fuera',
  'Smoke screen over an area for 20s: blocks sight both ways': 'Cortina de humo sobre una zona durante 20 s: bloquea la vista en ambos sentidos',
  'A stick of heavy bombs along the line: flattens houses, kills tanks': 'Una ristra de bombas pesadas a lo largo de la línea: arrasa casas, destruye tanques',
  'One heavy bomb, right on the spot: tanks, guns, houses': 'Una bomba pesada justo en el punto: tanques, cañones, casas',
  'Drops two rifle squads and an MG team where your side can see (3 toward pop)': 'Lanza dos pelotones de fusileros y un equipo de ametralladora donde tu bando ve (cuentan 3 de población)',
  'Fighters intercept the next enemy air strike over the area for 60s (not recon)': 'Los cazas interceptan el próximo ataque aéreo enemigo sobre la zona durante 60 s (no el reconocimiento)',
  'Heavy cover for infantry': 'Cobertura pesada para la infantería',
  'Cover for infantry': 'Cobertura para la infantería',
  'Slows infantry; tanks flatten it': 'Frena a la infantería; los tanques lo aplastan',
  'Stops vehicles; cover for infantry': 'Detiene vehículos; cobertura para la infantería',
  'A trench pit behind a horseshoe of sandbags. An MG, AT gun, mortar, flak gun or howitzer standing in the pit reaches 25% farther': 'Un pozo de trinchera tras una herradura de sacos terreros. Una ametralladora, cañón antitanque, mortero, antiaéreo u obús dentro del pozo alcanza un 25% más lejos',
  'Hidden from the enemy; goes off under the first enemy squad or vehicle': 'Oculto al enemigo; estalla bajo el primer pelotón o vehículo enemigo',
  'Across a river, up to 5 cells; aim it along the crossing': 'Sobre un río, hasta 5 casillas; oriéntalo a lo largo del cruce',
  'Shovels craters, flooded craters and sunken ground back to open ground, and clears rubble (a road gets its road back)': 'Rellena cráteres, cráteres inundados y terreno hundido hasta dejarlo llano, y retira escombros (un camino recupera su camino)',
  'Lifts the mines your side knows about: your own, and enemy ones a builder squad found by standing within {0} m': 'Retira las minas que tu bando conoce: las tuyas y las enemigas que un pelotón constructor encontró al estar a menos de {0} m',
  'Infantry within {0} m reinforce for manpower, at half the HQ\'s pace. One per player': 'La infantería a menos de {0} m se refuerza con mano de obra, a la mitad del ritmo del CG. Uno por jugador',
  'One straight trench from the first click to the second': 'Una trinchera recta del primer clic al segundo',
  'A sawtooth trench: more room on the same frontage': 'Una trinchera en zigzag: más espacio en el mismo frente',
  'Two rows, the second 6 m behind the first': 'Dos filas, la segunda 6 m detrás de la primera',
  'A crescent around the first click, bowed toward the second': 'Una media luna alrededor del primer clic, curvada hacia el segundo',
  'A circle around the first click, out to the second': 'Un círculo alrededor del primer clic, hasta el segundo',
  'A trench square with barbed wire on the side of the second click': 'Un cuadrado de trinchera con alambre de espino en el lado del segundo clic',
  'Hold fire': 'Alto el fuego',
  'shoot only when given an attack order (snipers and guns stay hidden)': 'disparar solo con orden de ataque (francotiradores y cañones siguen ocultos)',
  'Hold position': 'Mantener posición',
  'never move without an order, not even to cover': 'no moverse nunca sin orden, ni siquiera a cubierto',
  'Auto-retreat': 'Retirada automática',
  'run for home when below {0}% strength': 'volver a la base por debajo del {0}% de fuerza',
  'On a resource node: +1.5 MP/s': 'En un nodo de recursos: +1,5 MO/s',
  'Trains MGs and elite infantry': 'Entrena ametralladoras e infantería de élite',
  'Trains AT guns, tanks, rockets': 'Entrena cañones antitanque, tanques, cohetes',
  'Trains planes; their base': 'Entrena aviones; su base',
  'Shoots down planes over your base': 'Derriba aviones sobre tu base',
  'Concrete MG post: shrugs off rifles, weak from behind': 'Nido de ametralladora de hormigón: aguanta los fusiles, débil por detrás',
  'On the coast: trains landing craft': 'En la costa: entrena lanchas de desembarco',
  'Trains infantry': 'Entrena infantería',
  'Ready': 'Listo',
  'Flying out': 'Despegando',
  'On station': 'En posición',
  'Heading home': 'Volviendo a la base',
  'Rearming': 'Rearmándose',
  'Infantry': 'Infantería',
  'Support weapons': 'Armas de apoyo',
  'Vehicles': 'Vehículos',
  'Aircraft': 'Aviones',
  'Naval': 'Naval',
  'Hidden': 'Oculto',
  'Riding': 'A bordo',
  'Carrying a squad': 'Lleva un pelotón',
  'Retreating': 'Retirándose',
  'Reinforcing': 'Reforzando',
  'Suppressive fire': 'Fuego de supresión',
  'AP round loaded': 'Proyectil perforante cargado',
  'Pinned': 'Inmovilizado',
  'Suppressed': 'Suprimido',
  'In trench': 'En trinchera',
  'By cover': 'Junto a cobertura',
  'In cover': 'A cubierto',
  'Digging': 'Cavando',
  'Waiting for MP to dig': 'Esperando MO para cavar',
  'Garrisoned: {0}': 'Guarnecido: {0}',
  'Building {0}%': 'Construyendo {0}%',
  'Veteran: 1 star': 'Veterano: 1 estrella',
  'Veteran: {0} stars': 'Veterano: {0} estrellas',
  'Find the next idle unit. Shift+click selects all idle units': 'Busca la siguiente unidad ociosa. Shift+clic selecciona todas las ociosas',
  '{0}. Click to keep this type; Shift+click removes it': '{0}. Clic para quedarte solo con este tipo; Shift+clic lo quita',
  'Idle {0}': 'Ociosas {0}',
  '1 unit selected': '1 unidad seleccionada',
  '{0} units selected': '{0} unidades seleccionadas',
  'Selection': 'Selección',
  '{0}/{1} hp': '{0}/{1} PS',
  'Training {0} {1}% ({2}/5)': 'Entrenando {0} {1}% ({2}/5)',
  'Training {0} {1}%': 'Entrenando {0} {1}%',
  'Training {0} {1}%, then {2}': 'Entrenando {0} {1}%, después {2}',
  '{0} buildings training': '{0} edificios entrenando',
  ', then {0}': ', después {0}',
  'ranks of up to ten across the facing; a longer right-drag fits more side by side': 'filas de hasta diez de frente; un arrastre derecho más largo pone más en paralelo',
  'a square, widened by a longer right-drag': 'un cuadrado, más ancho con un arrastre derecho más largo',
  'two files deep, for roads and gaps': 'dos en fondo, para caminos y pasos',
  'an arrowhead, one unit at the tip': 'una punta de flecha, una unidad en la punta',
  'Line': 'Línea',
  'Block': 'Bloque',
  'Column': 'Columna',
  'Wedge': 'Cuña',
  'line': 'línea',
  'block': 'bloque',
  'column': 'columna',
  'wedge': 'cuña',
  'Form': 'Formar',
  'Formation': 'Formación',
  'Build': 'Construir',
  'Trench patterns': 'Patrones de trinchera',
  'Base': 'Base',
  'Defenses': 'Defensas',
  'Field works': 'Obras de campo',
  'Engineering': 'Ingeniería',
  '{0} ({1} cycles): {2}': '{0} ({1} alterna): {2}',
  'Tighten ({0}): closer spacing; the selection re-forms where it stands': 'Cerrar ({0}): menos separación; la selección se reagrupa donde está',
  'Spread ({0}): wider spacing; the selection re-forms where it stands': 'Abrir ({0}): más separación; la selección se reagrupa donde está',
  'Tighten': 'Cerrar',
  'Spread': 'Abrir',
  'Together': 'Juntos',
  'Snap': 'Ajustar',
  'March together: the group moves at the pace of its slowest unit and arrives in one piece': 'Marchar juntos: el grupo avanza al ritmo de su unidad más lenta y llega entero',
  'Snap to trenches: infantry placed within 3 m of a trench step into it': 'Ajustar a trincheras: la infantería colocada a menos de 3 m de una trinchera entra en ella',
  '{0}: {1}. Every selected builder squad digs; each segment is paid as it is started. Shift on the second click queues it. Right-click a planned pattern with other squads to send them to help': '{0}: {1}. Cava cada pelotón constructor seleccionado; cada tramo se paga al empezarlo. Shift en el segundo clic lo encola. Clic derecho sobre un patrón planeado con otros pelotones para mandarlos a ayudar',
  'Orders': 'Órdenes',
  'Retreat': 'Retirada',
  'Retreat ({0}): run back to base, heal and reinforce there': 'Retirada ({0}): volver corriendo a la base, curarse y reforzarse allí',
  'Attack-move': 'Avance de ataque',
  'Attack-move ({0}, or Ctrl+right-click): move and fight anything met on the way': 'Avance de ataque ({0}, o Ctrl+clic derecho): avanzar y combatir todo lo que encuentre',
  'Stop': 'Detener',
  'Stop ({0}): halt where they are': 'Detener ({0}): parar donde están',
  'Shell area': 'Bombardear zona',
  'Shell area ({0}): click any ground, seen or not; mortars, howitzers, rocket trucks and ships move into range and keep firing on it until given another order, bombers drop every stick on it. Shift+click queues it': 'Bombardear zona ({0}): haz clic en cualquier terreno, visto o no; morteros, obuses, camiones lanzacohetes y barcos se ponen a tiro y siguen disparando hasta recibir otra orden, los bombarderos sueltan allí todas sus bombas. Shift+clic lo encola',
  '{0} ({1}): {2}. Click to switch it on or off for the selection': '{0} ({1}): {2}. Clic para activarlo o desactivarlo en la selección',
  'Cover': 'Cubierto',
  'Take cover ({0}): infantry run to the nearest trench, wall or rubble within {1} m. Shift+click queues it': 'A cubierto ({0}): la infantería corre a la trinchera, muro o escombros más cercanos a menos de {1} m. Shift+clic lo encola',
  'Unload': 'Descargar',
  'Unload ({0}): the squad inside gets out beside the halftrack. To board, right-click the halftrack with infantry selected': 'Descargar ({0}): el pelotón de dentro baja junto al semioruga. Para embarcar, clic derecho sobre el semioruga con infantería seleccionada',
  'Formation: shape, spacing, marching together and snapping to trenches. Right-drag sets the facing and the width; double right-click turns to face a spot': 'Formación: forma, separación, marchar juntos y ajustar a trincheras. Arrastrar con clic derecho fija la orientación y el ancho; doble clic derecho gira hacia un punto',
  'Build: defenses, sandbags, wire, traps, mines, bridges and more': 'Construir: defensas, sacos terreros, alambre, obstáculos, minas, puentes y más',
  'Trench patterns: lines, zigzags, rings and strongpoints the builder squads dig together': 'Patrones de trinchera: líneas, zigzags, anillos y puntos fuertes que los pelotones constructores cavan juntos',
  '{0}: {1}, click where. {2}s cooldown. Right-click: autocast on/off': '{0}: {1}, haz clic en el objetivo. Recarga de {2} s. Clic derecho: uso automático sí/no',
  '{0}: {1}. {2}s cooldown. Right-click: autocast on/off': '{0}: {1}. Recarga de {2} s. Clic derecho: uso automático sí/no',
  'Form ▸': 'Formar ▸', 'Form ▾': 'Formar ▾',
  'Build ▸': 'Construir ▸', 'Build ▾': 'Construir ▾',
  'Trench ▸': 'Trinchera ▸', 'Trench ▾': 'Trinchera ▾',
  'No squad on board': 'Ningún pelotón a bordo',
  '{0}/seg': '{0}/tramo',
  'Recruiting': 'Reclutando',
  'Recruit': 'Reclutar',
  'A letter opens a group, a second letter buys from it (Q Q: Rifles); Shift+letter buys five. {0} goes back a step, {1} or a right-click stops': 'Una letra abre un grupo y una segunda compra de él (Q Q: Fusileros); Shift+letra compra cinco. {0} vuelve un paso, {1} o un clic derecho termina',
  'Recruit by letter ({0}): a letter opens a group, a second buys from it, Shift buys five. WASD pans again when you stop': 'Reclutar por letra ({0}): una letra abre un grupo, otra compra de él, Shift compra cinco. WASD vuelve a desplazar al terminar',
  'Rally ({0}): choose where new recruits gather': 'Reunión ({0}): elige dónde se reúnen los nuevos reclutas',
  'Rally': 'Reunión',
  'Under construction': 'En construcción',
  'Right-click it with Engineers to help': 'Haz clic derecho con Ingenieros para ayudar',
  'Cancel the building and get 75% of its cost back': 'Cancela el edificio y recupera el 75% de su coste',
  'Cancel': 'Cancelar',
  '75% back': 'recupera 75%',
  'Right-click the ground: rally point': 'Clic derecho en el suelo: punto de reunión',
  '{0}, trains in {1}s': '{0}, se entrena en {1} s',
  '{0} MP, {1}s': '{0} MO, {1} s',
  'Idle': 'Inactivo',
  'Scharfschützen': 'Scharfschützen',

  // ---------- keys.js (shortcut names and what they do) ----------
  'Stop selected units': 'Detiene las unidades seleccionadas',
  'Retreat selected units': 'Retira las unidades seleccionadas',
  'Use the first ready selected ability': 'Usa la primera habilidad lista de la selección',
  'Aim an attack-move order': 'Apunta una orden de avance de ataque',
  'Shell an area: mortars, howitzers, rocket trucks, ships and bombers keep firing on a spot': 'Bombardear zona: morteros, obuses, camiones lanzacohetes, barcos y bombarderos siguen disparando sobre un punto',
  'Selected infantry take cover': 'La infantería seleccionada se pone a cubierto',
  'Toggle hold fire': 'Activa alto el fuego',
  'Toggle hold position': 'Activa mantener posición',
  'Toggle auto-retreat': 'Activa retirada automática',
  'Cycle the formation: line, block, column, wedge': 'Cambia la formación: línea, bloque, columna, cuña',
  'Tighten the formation': 'Cierra la formación',
  'Spread the formation': 'Abre la formación',
  'Toggle audio': 'Activa o silencia el audio',
  'Unload the selected halftracks': 'Descarga los semiorugas seleccionados',
  'Jump to the newest alert, or center the selection': 'Salta a la última alerta o centra la selección',
  'Follow the selection': 'Sigue a la selección',
  'Set the army rally point': 'Fija el punto de reunión del ejército',
  'Go home and select the Classic HQ': 'Vuelve a la base y selecciona el CG de Clásico',
  'Clear the selection': 'Borra la selección',
  'Cancel targeting': 'Cancela la puntería',
  'Select the whole army': 'Selecciona todo el ejército',
  'Period': 'Punto',
  'Comma': 'Coma',
  'Select and center the next idle ground unit': 'Selecciona y centra la siguiente unidad terrestre ociosa',
  'Select all idle ground units': 'Selecciona todas las unidades terrestres ociosas',
  'Select and center the next idle Engineer': 'Selecciona y centra el siguiente Ingeniero ocioso',
  'Aim {0} support': 'Apunta el apoyo: {0}',
  'Place {0}': 'Colocar: {0}',
  'Place a {0}': 'Colocar: {0}',
  'All selected builders dig a trench line': 'Todos los constructores seleccionados cavan una línea de trinchera',
  'Up': 'Arriba',
  'Down': 'Abajo',
  'Left': 'Izquierda',
  'Right': 'Derecha',
  'Pan the camera': 'Desplaza la cámara',
  'Recall group {0}; tap twice to center': 'Recupera el grupo {0}; pulsa dos veces para centrar',
  'Set group {0}': 'Asigna el grupo {0}',
  'Append selection to group {0}': 'Añade la selección al grupo {0}',
  'Recruit by letter: turn the Command Card letters on or off': 'Reclutar por letra: activa o desactiva las letras de la Tarjeta de mando',
  'Explain how Classic trains by letter': 'Explica cómo se entrena por letra en Clásico',
  'Leave recruit mode': 'Sal del modo reclutamiento',
  'Buy the unit on card {0}': 'Compra la unidad de la carta {0}',
  'Buy five of the unit on card {0}': 'Compra cinco de la unidad de la carta {0}',

  // ---------- main.js: aiming hints, point labels ----------
  'Radio post ·': 'Puesto de radio ·',
  'Supply depot ·': 'Depósito de suministros ·',
  '★ {0}× VP': '★ {0}× PV',
  'Cut off: no supply': 'Aislado: sin suministro',
  'Locked: take the linked point first': 'Bloqueado: toma primero el punto vinculado',
  '{0} HQ': 'CG de {0}',
  'Click where to build the {0}. Right-click cancels': 'Haz clic donde construir: {0}. Clic derecho cancela',
  '{0} line': 'Línea de {0}',
  '{0}: click where it starts. Right-click cancels': '{0}: haz clic donde empieza. Clic derecho cancela',
  '{0}: nothing can be built there': '{0}: ahí no se puede construir nada',
  '{0}: 1 segment, {1} MP{2}': '{0}: 1 tramo, {1} MO{2}',
  '{0}: {1} segments, {2} MP{3}': '{0}: {1} tramos, {2} MO{3}',
  '{0}: 1 segment, {1} MP': '{0}: 1 tramo, {1} MO',
  '{0}: {1} segments, {2} MP': '{0}: {1} tramos, {2} MO',
  '{0}. Click {1}. Right-click cancels': '{0}. Haz clic {1}. Clic derecho cancela',
  'where it ends': 'donde termina',
  'the far side': 'en el lado opuesto',
  'Select a mortar, howitzer, rocket truck, destroyer or bomber to shell an area': 'Selecciona un mortero, obús, camión lanzacohetes, destructor o bombardero para bombardear una zona',
  'Click a resource node': 'Haz clic en un nodo de recursos',
  'Click where to build': 'Haz clic donde construir',
  'Click where to throw': 'Haz clic donde lanzar',
  'Click where to fire the salvo': 'Haz clic donde disparar la salva',
  'Click where to plant the charge': 'Haz clic donde colocar la carga',
  'Click where to attack-move': 'Haz clic hacia donde avanzar atacando',
  'Click the ground to shell (they keep firing until given another order)': 'Haz clic en el suelo a bombardear (siguen disparando hasta recibir otra orden)',
  'Click where recruits should gather': 'Haz clic donde deben reunirse los reclutas',
  'Click to set the center': 'Haz clic para fijar el centro',
  'Select a Production Building to set its rally': 'Selecciona un edificio de producción para fijar su punto de reunión',
  'Formation spacing {0}x': 'Separación de la formación {0}x',
  'Formation: {0}': 'Formación: {0}',
  'In Classic, select a Production Building and press the letters on its cards': 'En Clásico, selecciona un edificio de producción y pulsa las letras de sus cartas',
  'Move the mouse to rotate, then click to {0}': 'Mueve el ratón para girar y haz clic para {0}',
  'place it': 'colocarlo',
  'call it in': 'pedirlo',
  'Following {0}': 'Siguiendo a {0}',
  'Following the selection': 'Siguiendo a la selección',

  // ---------- unit, building, support and ability names ----------
  'Rifle Squad': 'Pelotón de fusileros',
  'Rifles': 'Fusileros',
  'MG Team': 'Equipo de ametralladora',
  'AT Gun': 'Cañón antitanque',
  'Light Tank': 'Tanque ligero',
  'Medium Tank': 'Tanque medio',
  'Rocket Launcher': 'Lanzacohetes',
  'Flak Gun': 'Cañón antiaéreo',
  'Fighter': 'Caza',
  'Ground-attack Plane': 'Avión de ataque a tierra',
  'Bomber': 'Bombardero',
  'Mobile Flak': 'Antiaéreo móvil',
  'Mortar Team': 'Equipo de mortero',
  'Sniper': 'Francotirador',
  'Armored Car': 'Vehículo blindado',
  'Halftrack': 'Semioruga',
  'Landing Craft': 'Lancha de desembarco',
  'Gunboat': 'Cañonero',
  'Destroyer': 'Destructor',
  'Medic Team': 'Equipo sanitario',
  'Engineer Squad': 'Pelotón de ingenieros',
  'Engineers': 'Ingenieros',
  'Flamethrower Squad': 'Pelotón lanzallamas',
  'Field Howitzer': 'Obús de campaña',
  'Tank Destroyer': 'Cazacarros',
  'Ranger Squad': 'Pelotón de rangers',
  'Command Bunker': 'Búnker de mando',
  'Conscripts': 'Reclutas',
  'Commandos': 'Comandos',
  'Tiger': 'Tiger',
  'Churchill': 'Churchill',
  'HQ': 'CG',
  'Headquarters': 'Cuartel general',
  'Supply Depot': 'Depósito de suministros',
  'Barracks': 'Cuartel',
  'Motor Pool': 'Parque móvil',
  'Airfield': 'Aeródromo',
  'Shipyard': 'Astillero',
  'Flak Emplacement': 'Emplazamiento antiaéreo',
  'Pillbox': 'Fortín',
  'Concrete Wall': 'Muro de hormigón',
  'Gate': 'Puerta',
  'Concrete, Engineers only: stops infantry and vehicles and blocks sight; explosives breach it a block at a time': 'Hormigón, solo ingenieros: detiene a la infantería y los vehículos y bloquea la vista; los explosivos lo abren bloque a bloque',
  'Three cells of wall that stand open for your side and allies, and shut while an enemy is within 16 m': 'Tres casillas de muro que quedan abiertas para tu bando y aliados, y se cierran mientras haya un enemigo a menos de 16 m',
  'Scout Tower': 'Torre de observación',
  'Timber lookout: sees 60 m over walls and houses': 'Atalaya de madera: ve a 60 m por encima de muros y casas',
  'Field Hospital': 'Hospital de campaña',
  'Production Building': 'Edificio de producción',
  'Recon Flight': 'Vuelo de reconocimiento',
  'Artillery Barrage': 'Barrera de artillería',
  'Strafing Run': 'Pasada de ametrallamiento',
  'Smoke Barrage': 'Barrera de humo',
  'Bombing Run': 'Pasada de bombardeo',
  'Dive Bomber': 'Bombardero en picado',
  'Paratroopers': 'Paracaidistas',
  'Fighter Cover': 'Cobertura de cazas',
  'Grenade': 'Granada',
  'Suppressive Fire': 'Fuego de supresión',
  'AP Round': 'Proyectil perforante',
  'Smoke': 'Humo',
  'Rocket Barrage': 'Salva de cohetes',
  'Mortar Barrage': 'Barrera de mortero',
  'Torpedo': 'Torpedo',
  'Shore Bombardment': 'Bombardeo costero',
  'Howitzer Barrage': 'Barrera de obús',
  'Satchel Charge': 'Carga de demolición',
  'Ura!': '¡Urá!',
  'Sandbags': 'Sacos terreros',
  'Barbed Wire': 'Alambre de espino',
  'Tank Traps': 'Erizos antitanque',
  'Gun Pit': 'Pozo de tirador',
  'Minefield': 'Campo de minas',
  'Bridge': 'Puente',
  'Fill in': 'Rellenar',
  'Clear mines': 'Desminar',
  'Trench': 'Trinchera',
  'Trench line': 'Línea de trinchera',
  'Zigzag trench': 'Trinchera en zigzag',
  'Double line': 'Doble línea',
  'Arc': 'Arco',
  'Ring': 'Anillo',
  'Strongpoint': 'Punto fuerte',
  'wooden shed': 'cobertizo de madera',
  'brick house': 'casa de ladrillo',
  'stone building': 'edificio de piedra',
  'church': 'iglesia',
  'factory': 'fábrica',
  // faction names that are descriptions, not models
  '.30 cal MG': 'Ametralladora cal. 30',
  '57mm AT Gun': 'Cañón antitanque de 57 mm',
  'Riflemen': 'Fusileros',
  'Grenadiers': 'Granaderos',
  'Medics': 'Sanitarios',
  'Sanitäter': 'Sanitäter',
  'Sniper Team': 'Equipo de francotiradores',
  'Snipers': 'Francotiradores',
  'Sniper Pair': 'Pareja de francotiradores',
  'Flamethrower Team': 'Equipo lanzallamas',
  'Flammenwerfer Team': 'Equipo Flammenwerfer',
  'ROKS-2 Flamethrower Team': 'Equipo lanzallamas ROKS-2',
  'Lifebuoy Flamethrower Team': 'Equipo lanzallamas Lifebuoy',
  'MG 42 Team': 'Equipo MG 42',
  '81mm Mortar': 'Mortero de 81 mm',
  '82mm Mortar': 'Mortero de 82 mm',
  '3-inch Mortar': 'Mortero de 3 pulgadas',
  'GrW 34 Mortar': 'Mortero GrW 34',
  '45mm AT Gun': 'Cañón antitanque de 45 mm',
  '61-K AA Gun': 'Cañón antiaéreo 61-K',
  'Maxim MG': 'Ametralladora Maxim',
  'Vickers MG': 'Ametralladora Vickers',
  'Rifle Section': 'Sección de fusileros',
  'Sanitary Team': 'Equipo sanitario',
  'Stretcher Bearers': 'Camilleros',
  'Assault Boat': 'Bote de asalto',
  'Armored Boat': 'Lancha blindada',
  'PT Boat': 'Lancha torpedera PT',
  'Fletcher Destroyer': 'Destructor Fletcher',
  'Gnevny Destroyer': 'Destructor Gnevny',
  'Tribal-class Destroyer': 'Destructor clase Tribal',
  'M2A1 105mm Howitzer': 'Obús M2A1 de 105 mm',
  '122mm M-30 Howitzer': 'Obús M-30 de 122 mm',
  'Daimler Armoured Car': 'Blindado Daimler',
  'M3 Half-track': 'Semioruga M3',
  'M5 Half-track': 'Semioruga M5',
  'M16 Half-track': 'Semioruga M16',
  'Universal Carrier': 'Transporte Universal',
  // unit roles (unit-roles.js)
  'Captures, all-round': 'Captura, polivalente',
  'Pins infantry, sets up': 'Inmoviliza infantería, se emplaza',
  'Kills tanks, sets up': 'Destruye tanques, se emplaza',
  'Kills infantry, weak rear': 'Mata infantería, retaguardia débil',
  'Rocket salvos, breaks garrisons': 'Salvas de cohetes, desaloja guarniciones',
  'Elite, bazookas, satchel charges': 'Élite, bazucas, cargas de demolición',
  'Heavy tank, thick front armor (max 1)': 'Tanque pesado, blindaje frontal grueso (máx. 1)',
  'Cheap waves, Ura! sprint': 'Oleadas baratas, carrera ¡Urá!',
  'Slow infantry tank, thickest front armor (max 1)': 'Tanque de infantería lento, el blindaje frontal más grueso (máx. 1)',
  'Raiders, Stens and satchels; hide when still': 'Incursores, Sten y cargas; se ocultan quietos',
  'Builds depots, weak rifles': 'Construye depósitos, fusiles débiles',
  'Arcing fire, out-ranges MGs': 'Tiro parabólico, supera el alcance de las ametralladoras',
  'One shot, one kill; hides when still': 'Un disparo, una baja; se oculta quieto',
  'Fast scout and raider': 'Explorador e incursor rápido',
  'Mainline tank': 'Tanque principal',
  'Shoots down enemy air support': 'Derriba el apoyo aéreo enemigo',
  'Flak that keeps up with the army': 'Antiaéreo que sigue el ritmo del ejército',
  'Clears the sky, escorts': 'Limpia el cielo, escolta',
  'Rockets and bombs on ground targets': 'Cohetes y bombas sobre objetivos terrestres',
  'Carries one squad; infantry reinforce beside it': 'Lleva un pelotón; la infantería se refuerza a su lado',
  'Unarmed; heals squads out of the fight': 'Desarmado; cura pelotones fuera del combate',
  'Carries one squad over water, lands it on a beach': 'Lleva un pelotón por el agua y lo desembarca en una playa',
  'Fast; hunts boats, torpedoes ships': 'Rápido; caza botes, torpedea barcos',
  'Shells whatever your side spots, 120 m (max 2)': 'Bombardea lo que tu bando avista, 120 m (máx. 2)',
  'Long gun, hunts tanks; weak vs infantry': 'Cañón largo, caza tanques; débil contra infantería',
  'Heavy shells at 95 m; slow, sets up, blind up close': 'Proyectiles pesados a 95 m; lento, se emplaza, ciego de cerca',
  'Burns out houses and trenches; short range': 'Quema casas y trincheras; corto alcance',
  'Drops bomb sticks on crowds and dug-in positions': 'Suelta ristras de bombas sobre grupos y posiciones atrincheradas',
  'Unit': 'Unidad',
  'Aim': 'Apuntar',
  'click the center, move to turn, click to call it in': 'clic en el centro, mueve para girar, clic para pedirlo',
  'Click the spot to call it in': 'Haz clic en el punto para pedirlo',
  '{0} ({1}): {2}': '{0} ({1}): {2}',
  // unit portraits (symbols.js, read aloud by screen readers)
  'Rifleman: a helmeted soldier with his rifle held up across his chest': 'Fusilero: un soldado con casco y el fusil cruzado sobre el pecho',
  'Conscripts: two soldiers in side caps and greatcoats, one behind the other': 'Reclutas: dos soldados con gorro y capote, uno detrás del otro',
  'Ranger: a soldier advancing in a long stride, submachine gun held forward': 'Ranger: un soldado avanzando a zancadas, con el subfusil al frente',
  'Sniper: a prone soldier aiming a long rifle with a telescopic sight, on a bipod': 'Francotirador: un soldado tumbado apuntando un fusil largo con mira telescópica, sobre un bípode',
  'Engineer: a soldier sweeping a mine detector over the ground ahead': 'Ingeniero: un soldado pasando un detector de minas por el suelo',
  'Flamethrower: a soldier with fuel tanks on his back, the flame gun at his hip spitting a tongue of fire': 'Lanzallamas: un soldado con depósitos a la espalda y la lanza a la cadera escupiendo fuego',
  'Medic: a soldier beside a medical cross': 'Sanitario: un soldado junto a una cruz médica',
  'Machine gun team: a prone gunner behind a machine gun on its tripod': 'Equipo de ametralladora: un tirador tumbado tras una ametralladora sobre trípode',
  'Mortar team: a kneeling loader holding a bomb beside a mortar on its bipod and baseplate': 'Equipo de mortero: un cargador de rodillas con una granada junto a un mortero',
  'Anti-tank gun: a long barrel with a muzzle brake behind a sloped shield, on a wheel and a split trail': 'Cañón antitanque: un tubo largo con freno de boca tras un escudo inclinado, sobre ruedas',
  'Field howitzer: a heavy barrel raised steeply behind a shield, on a big wheel and a split trail': 'Obús de campaña: un tubo pesado muy elevado tras un escudo, sobre una gran rueda',
  'Anti-aircraft gun: a light cannon raised steeply on a cross-shaped ground mount': 'Cañón antiaéreo: un cañón ligero muy elevado sobre un afuste en cruz',
  'Halftrack: an open-topped carrier with a wheel in front and a track behind': 'Semioruga: un transporte abierto con ruedas delante y orugas detrás',
  'Landing craft: a flat boxy boat with a square bow ramp, riding on the water': 'Lancha de desembarco: un bote plano con rampa de proa, sobre el agua',
  'Gunboat: a long low motor boat with a raised bridge and a gun aft, riding on the water': 'Cañonero: una lancha larga y baja con puente elevado y un cañón a popa',
  'Destroyer: a long warship with gun mounts fore and aft, a bridge and two funnels': 'Destructor: un buque de guerra largo con cañones a proa y popa, puente y dos chimeneas',
  'Armored car: an angled armored body on two axles with a small turret and a short gun': 'Vehículo blindado: un casco anguloso de dos ejes con torreta pequeña y cañón corto',
  'Self-propelled flak: a half-track with twin anti-aircraft barrels raised on its open bed': 'Antiaéreo autopropulsado: un semioruga con dos tubos antiaéreos elevados',
  'Light tank: a small tank with a short gun': 'Tanque ligero: un tanque pequeño con cañón corto',
  'Medium tank: a sloped front, a rounded turret with a cupola and a medium gun': 'Tanque medio: frontal inclinado, torreta redondeada con cúpula y cañón medio',
  'Heavy tank: a boxy hull and turret, big road wheels and a long gun with a muzzle brake': 'Tanque pesado: casco y torreta cuadrados, grandes ruedas y cañón largo con freno de boca',
  'Infantry tank: a long, tall hull with tracks running over the top, a small square turret and a short gun': 'Tanque de infantería: casco largo y alto con orugas por encima, torreta cuadrada pequeña y cañón corto',
  'Tank destroyer: a low casemate with no turret and a long gun out of its sloped front': 'Cazacarros: una casamata baja sin torreta y un cañón largo en el frontal inclinado',
  'Rocket artillery: a truck with a rack of launch rails raised over the cab': 'Artillería de cohetes: un camión con rieles de lanzamiento sobre la cabina',
  'Fighter: a single-engine plane with tapered wings, seen from above': 'Caza: un avión monomotor de alas afiladas, visto desde arriba',
  'Ground-attack plane: a heavy plane with broad straight wings and rockets under them, seen from above': 'Avión de ataque: un avión pesado de alas rectas con cohetes debajo, visto desde arriba',
  'Bomber: a twin-engine plane with long straight wings and a twin tail, seen from above': 'Bombardero: un bimotor de alas largas y rectas con doble cola, visto desde arriba',
  'Bunker: a low concrete blockhouse with a firing slit, on an earth berm': 'Búnker: un fortín bajo de hormigón con aspillera, sobre un terraplén',
  'Headquarters: a command tent with a flag on a pole': 'Cuartel general: una tienda de mando con bandera',
  'Supply depot: stacked supply crates and a fuel drum': 'Depósito de suministros: cajas apiladas y un bidón de combustible',
  'Barracks: a long hut with a pitched roof, a chimney, windows and a door': 'Cuartel: un barracón alargado con tejado a dos aguas, chimenea, ventanas y puerta',
  'Motor pool: an open repair shed with a big wrench inside': 'Parque móvil: un taller abierto con una gran llave inglesa',
  'Airfield: an arched hangar with its doors open': 'Aeródromo: un hangar abovedado con las puertas abiertas',
  'Shipyard: a slipway running down into the water under a crane': 'Astillero: una grada que baja al agua bajo una grúa',
  'Flak emplacement: a ring of sandbags with an anti-aircraft gun pointing up': 'Emplazamiento antiaéreo: un anillo de sacos terreros con un cañón antiaéreo apuntando arriba',
  'Recon flight: a pair of binoculars': 'Vuelo de reconocimiento: unos prismáticos',
  'Artillery barrage: a shell falling onto a burst': 'Barrera de artillería: un proyectil cayendo sobre una explosión',
  'Strafing run: a fighter diving with tracer fire ahead of it': 'Pasada de ametrallamiento: un caza en picado con trazadoras',
  'Smoke barrage: a cloud of smoke': 'Barrera de humo: una nube de humo',
  'Bombing run: a stick of three bombs falling, fins up': 'Pasada de bombardeo: tres bombas cayendo',
  'Dive bomber: a plane diving with a bomb released ahead of it': 'Bombardero en picado: un avión en picado soltando una bomba',
  'Paratroopers: a soldier hanging under a parachute': 'Paracaidistas: un soldado colgando de un paracaídas',
  'Fighter cover: a shield with a fighter cut out of it': 'Cobertura de cazas: un escudo con la silueta de un caza',
  'Commando: a raider advancing with a submachine gun': 'Comando: un incursor avanzando con un subfusil',
  'Unknown type: a question mark in a square': 'Tipo desconocido: un signo de interrogación en un cuadrado',

  // ---------- weather ----------
  'Map default': 'Predeterminado del mapa',
  'Map default: {0}': 'Predeterminado del mapa: {0}',
  'Clear': 'Despejado',
  'Ground fog': 'Niebla baja',
  'Rain': 'Lluvia',
  'Snow': 'Nieve',
  'Random': 'Aleatorio',
  'Mud': 'Barro',
  'Fog': 'Niebla',
  '{0} until {1}': '{0} hasta {1}',
  '{0} in {1} s': '{0} en {1} s',
  '{0} at {1}': '{0} a las {1}',
  'Rain: vehicles slow off the road, fords deeper, sight shorter': 'Lluvia: vehículos lentos fuera del camino, vados más hondos, menos visión',
  'Wet ground ({0}%): vehicles slow off the road': 'Suelo mojado ({0}%): vehículos lentos fuera del camino',
  '{0}. Showers come and go': '{0}. Los chubascos van y vienen',
  'Picked when the match starts. Fog may lift or rain may turn to mud partway through': 'Se elige al empezar la partida. La niebla puede levantarse o la lluvia volverse barro a mitad',
  'The weather this map brings': 'El clima que trae este mapa',
  'Weather for this match. Planes and recon flights fly above it': 'Clima de esta partida. Los aviones y vuelos de reconocimiento vuelan por encima',
  'sight {0}': 'visión {0}',
  'infantry {0}': 'infantería {0}',
  'vehicles {0}': 'vehículos {0}',
  'vehicles {0} off roads': 'vehículos {0} fuera de caminos',
  'no effect': 'sin efecto',
  'Clear skies': 'Cielo despejado',
  'Fog lifting': 'La niebla se levanta',
  'Rain turning to mud': 'La lluvia se vuelve barro',

  // ---------- map names that are descriptions ----------
  'Default': 'Predeterminado',
  'Helms Deep': 'El Abismo de Helm',
  'King Of The Hill': 'Rey de la colina',
  'No Mans Land': 'Tierra de nadie',
  'Hot Gates': 'Las Termópilas',
  'Crater Field': 'Campo de cráteres',
  'Crossroads Village': 'Pueblo del cruce',
  'Island Towns': 'Pueblos isleños',
  'King of the Hill': 'Rey de la colina',
  'No Man\'s Land': 'Tierra de nadie',
  'River Towns': 'Pueblos del río',
  'Seawall': 'Malecón',
  'Seawall XL': 'Malecón XL',
  'Six Fronts': 'Seis frentes',
  'Stalingrad Factory': 'Fábrica de Stalingrado',
  'Test Arena': 'Arena de pruebas',
  'The Great Bridge': 'El gran puente',
  'The Hot Gates': 'Las Termópilas',
  'The Polder': 'El pólder',
  'Three Islands': 'Tres islas',
  'Twin Valleys': 'Valles gemelos',
  'Ardennes Crossing': 'Cruce de las Ardenas',
  'Kasserine Pass': 'Paso de Kasserine',
  'Pegasus Bridge': 'Puente Pegasus',
  'Pegasus Bridge XL': 'Puente Pegasus XL',
  'Hill 112': 'Colina 112',
  'Hill 112 XL': 'Colina 112 XL',
  'Helm\'s Deep': 'El Abismo de Helm',

  // ---------- public lobby (public-lobby.html / .js) ----------
  'Three Crossroads | Find a match': 'Three Crossroads | Buscar partida',
  'MULTIPLAYER HEADQUARTERS': 'CUARTEL GENERAL MULTIJUGADOR',
  'WW2 tactics. Take ground. Hold the line.': 'Táctica de la 2.ª Guerra Mundial. Gana terreno. Mantén la línea.',
  'PUBLIC ALPHA': 'ALFA PÚBLICA',
  'Your name': 'Tu nombre',
  'Quick Play': 'Partida rápida',
  'Join an open Conquest lobby, or start one. No account needed.': 'Únete a una sala de Conquista abierta o crea una. No hace falta cuenta.',
  'Refresh': 'Actualizar',
  'All modes': 'Todos los modos',
  'Open seats only': 'Solo con puestos libres',
  'Connecting…': 'Conectando…',
  'Match / map': 'Partida / mapa',
  'Seats': 'Puestos',
  'Status': 'Estado',
  'Action': 'Acción',
  'No public matches yet. Create one and invite the first players.': 'Aún no hay partidas públicas. Crea una e invita a los primeros jugadores.',
  'Create a match': 'Crear una partida',
  'Match name': 'Nombre de la partida',
  'Visibility': 'Visibilidad',
  'Public: shown in the match browser': 'Pública: aparece en el buscador de partidas',
  'Unlisted: share the room link': 'Oculta: comparte el enlace de la sala',
  'Choose the map, mode, teams and AI inside the room. Unlisted is not password-protected.': 'Elige mapa, modo, equipos e IA dentro de la sala. Oculta no está protegida con contraseña.',
  'Create match': 'Crear partida',
  'Have a room code?': '¿Tienes un código de sala?',
  'Room code': 'Código de sala',
  'Join room': 'Unirse a la sala',
  'Existing room links still work. A new code creates an unlisted room.': 'Los enlaces de sala existentes siguen funcionando. Un código nuevo crea una sala oculta.',
  'Best played on a desktop with a mouse and keyboard.': 'Mejor en un ordenador con ratón y teclado.',
  'Live rooms refresh every 5 seconds.': 'Las salas activas se actualizan cada 5 segundos.',
  'No downloads. No accounts.': 'Sin descargas. Sin cuentas.',
  'Player identity': 'Identidad del jugador',
  'Soldier': 'Soldado',
  'Open skirmish': 'Escaramuza abierta',
  'e.g. crossroads': 'p. ej. crossroads',
  '1 human': '1 humano',
  '{0} humans': '{0} humanos',
  '1 human · {0} AI': '1 humano · {0} IA',
  '{0} humans · {1} AI': '{0} humanos · {1} IA',
  'In progress': 'En curso',
  'Open': 'Abierta',
  'No matches fit these filters.': 'Ninguna partida cumple estos filtros.',
  'Directory unavailable': 'Directorio no disponible',
  'Invalid directory': 'Directorio no válido',
  '1 public match · Live': '1 partida pública · En vivo',
  '{0} public matches · Live': '{0} partidas públicas · En vivo',
  'Cannot reach the match server. Retry with Refresh.': 'No se puede conectar con el servidor. Reintenta con Actualizar.',
  'The directory is unavailable or still loading. Please try again.': 'El directorio no está disponible o aún está cargando. Inténtalo de nuevo.',
  'Watch': 'Mirar',
  'Lobby': 'Sala',
  'Playing': 'Jugando',

  // ---------- map editor (/?edit) ----------
  'Select / move': 'Seleccionar / mover',
  'Ground': 'Terreno',
  'Building': 'Edificio',
  'Hedgerow': 'Seto',
  'Wall': 'Muro',
  'Crater': 'Cráter',
  'River': 'Río',
  'Ford': 'Vado',
  'Rubble': 'Escombros',
  'Road': 'Camino',
  'Mine': 'Mina',
  'Woods': 'Bosque',
  'Raise ground': 'Elevar terreno',
  'Lower / dig': 'Bajar / cavar',
  'Capture point': 'Punto de captura',
  'Spawn': 'Punto de inicio',
  'New blank': 'Nuevo en blanco',
  'Show the map as each mode sets it up (editing is paused)': 'Muestra el mapa como lo prepara cada modo (la edición queda en pausa)',
  'Brush': 'Pincel',
  'right-drag erases / lowers': 'arrastrar con clic derecho borra / baja',
  'Preview': 'Vista previa',
  'Editing': 'Edición',
  'Title': 'Título',
  'Password': 'Contraseña',
  'Save': 'Guardar',
  'Fairness test': 'Prueba de equilibrio',
  'Back to the game': 'Volver al juego',
  'stone bridge': 'puente de piedra',
  'New map': 'Mapa nuevo',
  '(Assault only)': '(solo Asalto)',
  'not used in {0}': 'no se usa en {0}',
  'player {0}': 'jugador {0}',
  'Spawn {0}: {1}': 'Inicio {0}: {1}',
  '{0} spawns usable{1}': '{0} puntos de inicio utilizables{1}',
  '{0} defend, {1} attack, {2} bunker(s) (grey), {3} trench/wall cells added, clock {4} min{5}': '{0} defienden, {1} atacan, {2} búnker(es) (gris), {3} casillas de trinchera/muro añadidas, reloj {4} min{5}',
  'an HQ on every player\'s spawn, {0} MP nodes (yellow), {1} Fuel nodes (orange), points pay Munitions': 'un CG en el inicio de cada jugador, {0} nodos de MO (amarillo), {1} nodos de combustible (naranja), los puntos dan munición',
  'one shared HQ and bunker (grey), the horde enters at {0} spawn(s)': 'un CG y un búnker compartidos (gris), la horda entra por {0} punto(s) de inicio',
  'Horde needs defend spawns and at most 5 players: this preview is Conquest': 'La Horda necesita inicios de defensa y como máximo 5 jugadores: esta vista previa es Conquista',
  'Editing is paused: pick Editing to change the map.': 'La edición está en pausa: elige Edición para cambiar el mapa.',
  'spawn {0} can\'t reach point {1}': 'el inicio {0} no puede llegar al punto {1}',
  '✓ playable': '✓ jugable',
  'Delete': 'Borrar',
  'Radio post: faster support cooldowns for the side holding it. Supply depot: reinforces and repairs like home': 'Puesto de radio: recarga más rápida del apoyo para el bando que lo tiene. Depósito de suministros: refuerza y repara como en la base',
  'Point {0}: VP/s': 'Punto {0}: PV/s',
  'Kind': 'Tipo',
  'Radio post': 'Puesto de radio',
  'Supply depot': 'Depósito de suministros',
  'A side can only take this point while it holds the one picked here': 'Un bando solo puede tomar este punto mientras tenga el elegido aquí',
  'Needs': 'Necesita',
  'Select tool: click a structure, spawn or point to pick it, drag to move it': 'Herramienta de selección: clic en una estructura, inicio o punto para elegirlo, arrastra para moverlo',
  'Capture point tool: click to add, click one to edit it': 'Herramienta de punto de captura: clic para añadir, clic en uno para editarlo',
  '{0} tool: click to place it': 'Herramienta {0}: clic para colocarlo',
  '{0} tool: click or drag, right-drag does the opposite': 'Herramienta {0}: clic o arrastrar, con clic derecho hace lo contrario',
  '{0} tool: click or drag to paint, right-drag erases': 'Herramienta {0}: clic o arrastrar para pintar, con clic derecho borra',
  'barbed wire': 'alambre de espino',
  'tank traps': 'erizos antitanque',
  'Spawn {0}: drag to move, Delete removes it (later spawns renumber)': 'Inicio {0}: arrastra para mover, Supr lo quita (los siguientes se renumeran)',
  'Assault only (e.g. inside the defenders\' fortress; other modes skip it)': 'Solo Asalto (p. ej. dentro de la fortaleza defensora; los demás modos lo ignoran)',
  'Selected {0} ({1} cells): drag to move, Delete removes, Esc deselects': 'Seleccionado {0} ({1} casillas): arrastra para mover, Supr lo quita, Esc deselecciona',
  'Type': 'Tipo',
  'Name: lowercase letters, digits and dashes': 'Nombre: minúsculas, dígitos y guiones',
  'Fix the warnings first': 'Corrige antes los avisos',
  'Saved as "{0}". Pick it in the lobby.': 'Guardado como "{0}". Elígelo en la sala.',
  'Not saved: {0}': 'No guardado: {0}',
  'Running AI matches...': 'Jugando partidas de IA...',
  'Matches too long: most hit the 30 min cap. Add capture points or raise their VP.': 'Partidas demasiado largas: la mayoría llega al límite de 30 min. Añade puntos de captura o sube sus PV.',
  'Too few finished matches to judge fairness.': 'Muy pocas partidas terminadas para juzgar el equilibrio.',
  'Unfair: a spawn wins far more or less than its share.': 'Desequilibrado: un punto de inicio gana mucho más o menos de lo que le toca.',
  '✓ Looks fair': '✓ Parece equilibrado',
  '{0}/{1} matches, spawn wins {2}': '{0}/{1} partidas, victorias por inicio {2}',
  'avg {0} min, 2nd place at {1}% of winner{2}': 'media {0} min, el 2.º al {1}% del ganador{2}',
  'wrong password': 'contraseña incorrecta',
  'map too large': 'mapa demasiado grande',
  'bad JSON': 'JSON no válido',
  'bad map name': 'nombre de mapa no válido',
  'no such map': 'no existe ese mapa',
  'not a map': 'no es un mapa',

  // ---------- tutorial (shared/tutorial.js) and its lobby button ----------
  'Tutorial': 'Tutorial',
  'New here? Learn the basics in about ten minutes': '¿Eres nuevo? Aprende lo básico en unos diez minutos',
  'Objective: {0}': 'Objetivo: {0}',
  'Learn to play: Sergeant Hollis walks you from a glider landing to a bridge, one order at a time. Friends can join as co-op.': 'Aprende a jugar: el sargento Hollis te lleva desde el aterrizaje del planeador hasta un puente, orden a orden. Tus amigos pueden unirse en cooperativo.',
  'when the bridge was taken': 'al tomar el puente',
  'The bridge is ours. Training complete: you are ready for a real match.': 'El puente es nuestro. Entrenamiento completado: estás listo para una partida de verdad.',
  'Our base is under attack!': '¡Nuestra base está bajo ataque!',
  'Move your squads up to the hedgerow': 'Lleva tus pelotones hasta el seto',
  'Sgt. Hollis: Morning, Lieutenant. The glider pilot missed the field by two miles, so we walk.': 'Sgto. Hollis: Buenos días, teniente. El piloto del planeador falló el campo por tres kilómetros, así que toca caminar.',
  'Drag a box over the boys to select them, then right-click to move. Hedgerow first.': 'Arrastra un recuadro sobre los muchachos para seleccionarlos y haz clic derecho para moverlos. Primero, el seto.',
  'Clear the enemy sentries out of the orchard': 'Echa a los centinelas enemigos del huerto',
  'Two enemy sentry posts in the orchard. Right-click an enemy to attack it.': 'Dos puestos de centinelas enemigos en el huerto. Haz clic derecho sobre un enemigo para atacarlo.',
  'Shell holes, hedges and woods halve the hits you take. Open fields get men killed.': 'Los cráteres, setos y bosques reducen a la mitad los impactos que recibes. En campo abierto mueren hombres.',
  'Take the crossroads: keep a squad by the flag': 'Toma el cruce: deja un pelotón junto a la bandera',
  'Orchard is clear. Now the crossroads: park a squad by the flag until it turns our colour.': 'Huerto despejado. Ahora el cruce: deja un pelotón junto a la bandera hasta que tome nuestro color.',
  'Points pay manpower, and manpower buys men.': 'Los puntos dan mano de obra, y la mano de obra compra hombres.',
  'Recruit an AT gun: Tab, W, E, or click its card': 'Recluta un cañón antitanque: Tab, W, E, o haz clic en su carta',
  'Bad news from the farm: an enemy tank is fuelling up. Rifles cannot scratch armour.': 'Malas noticias de la granja: un tanque enemigo está repostando. Los fusiles no arañan el blindaje.',
  'Recruit an AT gun: press Tab, then W, then E. Or click its card at the bottom. HQ sent you the manpower.': 'Recluta un cañón antitanque: pulsa Tab, luego W y luego E. O haz clic en su carta abajo. El CG te ha enviado la mano de obra.',
  'Knock out the tank with your AT gun': 'Destruye el tanque con tu cañón antitanque',
  'Here it comes down the road! Set the AT gun where it can see the road and let the tank come to it.': '¡Ahí viene por el camino! Pon el cañón antitanque donde vea el camino y deja que el tanque se acerque.',
  'Keep the rifles out of its way. Hit it from the side or behind and it hurts twice as much.': 'Aparta a los fusileros de su camino. Si le das de lado o por detrás, le duele el doble.',
  'Clear the farm trench. Rifles: F throws a grenade': 'Limpia la trinchera de la granja. Fusileros: F lanza una granada',
  'They still hold the farm trench. Men in a trench shrug off bullets, not grenades.': 'Aún tienen la trinchera de la granja. Los hombres en trinchera aguantan las balas, no las granadas.',
  'Select a rifle squad, press F and click the trench. Your MG can pin them down first.': 'Selecciona un pelotón de fusileros, pulsa F y haz clic en la trinchera. Tu ametralladora puede inmovilizarlos antes.',
  'Send a squad home to refill: select it and press R': 'Manda un pelotón a la base a reponerse: selecciónalo y pulsa R',
  'Good work, but the boys are bleeding. Select a squad and press R: they run for home.': 'Buen trabajo, pero los muchachos sangran. Selecciona un pelotón y pulsa R: vuelven corriendo a la base.',
  'Near the HQ a squad gets its men back, for manpower. A live veteran beats a dead hero.': 'Cerca del CG un pelotón recupera sus hombres, a cambio de mano de obra. Más vale un veterano vivo que un héroe muerto.',
  'Shell the stone house: press C, click it, aim, click': 'Bombardea la casa de piedra: pulsa C, haz clic en ella, apunta, clic',
  'Last stop, the bridge. The enemy holds the stone house beside it, and stone eats bullets.': 'Última parada, el puente. El enemigo tiene la casa de piedra de al lado, y la piedra se traga las balas.',
  'Call artillery: press C, click the house, move the mouse to aim the barrage and click again.': 'Pide artillería: pulsa C, haz clic en la casa, mueve el ratón para orientar la barrera y vuelve a hacer clic.',
  'Cross the bridge and take the bridgehead': 'Cruza el puente y toma la cabeza de puente',
  'Shells away! When they land, push across and take the bridgehead.': '¡Proyectiles en camino! Cuando caigan, cruza y toma la cabeza de puente.',
  'Anyone left in that house will fight for it. Finish them, then hold the flag.': 'Quien quede en esa casa luchará por ella. Acaba con ellos y mantén la bandera.',
  'Record here with 1 defender: wave {0} in {1} ({2}).': 'Récord aquí con 1 defensor: oleada {0} en {1} ({2}).',
  'Record here with {0} defenders: wave {1} in {2} ({3}).': 'Récord aquí con {0} defensores: oleada {1} en {2} ({3}).',
  'No record yet here with 1 defender.': 'Todavía no hay récord aquí con 1 defensor.',
  'No record yet here with {0} defenders.': 'Todavía no hay récord aquí con {0} defensores.',
  'Land Mattress': 'Land Mattress',
  // HQ tiers and the Armory
  'Platoon HQ': 'CG de pelotón', 'Company HQ': 'CG de compañía', 'Battalion HQ': 'CG de batallón',
  'Needs {0}': 'Necesita: {0}', 'Upgrade to {0}': 'Mejorar a {0}', 'Top tier': 'Nivel máximo',
  'Armory': 'Armería', 'Researches weapon and armor upgrades': 'Investiga mejoras de armas y blindaje',
  'Infantry Weapons {0}': 'Armas de infantería {0}', 'Vehicle Guns {0}': 'Cañones de vehículos {0}', 'Vehicle Armor {0}': 'Blindaje de vehículos {0}',
  '{0} researched': 'Investigado: {0}', 'Needs a higher HQ tier': 'Necesita un CG de nivel superior',
  'Fully researched': 'Investigación completa', 'Already researching': 'Ya se está investigando',
  'Needs a finished {0}': 'Necesita: {0} terminado', 'Each Armory researches one line at a time': 'Cada Armería investiga una línea a la vez',
  'The next HQ tier unlocks new buildings and units. Research pauses while you have no finished HQ': 'El siguiente nivel de CG desbloquea edificios y unidades. La investigación se pausa mientras no tengas un CG terminado',
  // World Conquest victory
  'Own {0} of the {1} regions, or be the last nation standing. Destroy military bases, then claim with infantry': 'Controla {0} de las {1} regiones o sé la última nación en pie. Destruye las bases militares y luego reclama con infantería',
  'Your team must own every region. Destroy military bases, then claim with infantry': 'Tu equipo debe controlar todas las regiones. Destruye las bases militares y luego reclama con infantería',
  'Every rival nation has fallen.': 'Todas las naciones rivales han caído.', 'Your nation has fallen.': 'Tu nación ha caído.',
  'Your side controls the continent.': 'Tu bando controla el continente.', 'Another side controls the continent.': 'Otro bando controla el continente.',
  'No side controls the continent.': 'Ningún bando controla el continente.',
  'Paratroopers fly from one of your finished Airfields, at most {0} m away': 'Los paracaidistas despegan de uno de tus aeródromos terminados, a {0} m como máximo',
  'Save match': 'Guardar partida', 'Saved matches': 'Partidas guardadas', 'Load': 'Cargar', 'autosave': 'autoguardado',
  "Save this match to load it again later from this room's lobby": 'Guarda esta partida para cargarla más tarde desde la sala de esta partida',
  "Match saved. Load it from this room's lobby": 'Partida guardada. Cárgala desde la sala de esta partida',
  'The match could not be saved or loaded': 'No se pudo guardar ni cargar la partida',
  'Scout a hidden continent, destroy regional military bases, then claim regions with infantry. Build your own bases on owned territory. Your side wins by owning 60% of the regions or by outlasting every rival nation. No clock. Saves itself every 2 minutes.': 'Explora un continente oculto, destruye las bases militares regionales y luego reclama regiones con infantería. Construye tus propias bases en territorio propio. Tu bando gana al controlar el 60% de las regiones o al sobrevivir a todas las naciones rivales. Sin reloj. Se guarda sola cada 2 minutos.',
  'Rail moves start within {0} m of one of your stations and go to another station on your land': 'Los traslados en tren salen a {0} m como máximo de una de tus estaciones y van a otra estación en tu territorio',
  'No open line: every region on the way must be yours and its bridges standing': 'No hay línea abierta: todas las regiones del trayecto deben ser tuyas y sus puentes seguir en pie',
  'Too close to the railway or a station': 'Demasiado cerca del ferrocarril o de una estación',
  'Train': 'Tren', 'Station': 'Estación', 'Send by rail': 'Enviar en tren',
  'Troop Truck': 'Camión de tropas', 'Riding on a tank': 'Montados en un tanque', 'Marching': 'En marcha',
  // transports: troop trucks, tank riders, mount up
  'Unload the selected carriers: halftracks, trucks, boats and tanks with riders': 'Descarga los transportes seleccionados: semiorugas, camiones, lanchas y tanques con infantería encima',
  'Mount up: selected infantry board the nearest selected truck, halftrack or tank': 'Montar: la infantería seleccionada sube al camión, semioruga o tanque seleccionado más cercano',
  'Mount up ({0}): each selected squad climbs into or onto the nearest selected truck, halftrack or tank with a free seat': 'Montar ({0}): cada pelotón seleccionado sube al camión, semioruga o tanque seleccionado más cercano con plazas libres',
  'Unload ({0}): every squad aboard gets out beside its carrier. To board, right-click your own truck, halftrack, boat or tank with infantry selected': 'Descargar ({0}): todos los pelotones a bordo bajan junto a su transporte. Para embarcar, clic derecho sobre tu camión, semioruga, lancha o tanque con infantería seleccionada',
  'Carrying {0} of {1} squads': 'Lleva {0} de {1} pelotones', 'No free seats': 'No quedan plazas libres', '{0} free': '{0} libres',
  'Send by rail (World Conquest): ground units near your station ride to your station nearest a click': 'Enviar en tren (Conquista mundial): las unidades terrestres junto a tu estación viajan a tu estación más cercana al clic',
  'Send by rail ({0}): click a destination. Units within {1} m of one of your stations board a train (up to {2}) to your station nearest the click; every region on the way must be yours and its bridges standing. Each station sends one train every {3} s': 'Enviar en tren ({0}): haz clic en un destino. Las unidades a menos de {1} m de una de tus estaciones suben a un tren (hasta {2}) hacia tu estación más cercana al clic; cada región del trayecto debe ser tuya y sus puentes deben seguir en pie. Cada estación envía un tren cada {3} s',
  'Click the destination: they ride to your station nearest it': 'Haz clic en el destino: viajan a tu estación más cercana a él',
  'Select ground units near one of your stations to send them by rail': 'Selecciona unidades terrestres junto a una de tus estaciones para enviarlas en tren',
  'Train: a steam locomotive seen from the side, cab at the back, boiler and chimney in front': 'Tren: una locomotora de vapor vista de lado, la cabina detrás, la caldera y la chimenea delante',
  'Carries three squads fast; unarmed, thin-skinned': 'Lleva tres pelotones deprisa; sin armas y sin blindaje',
  'Troop truck: a lorry with a round-topped canvas tilt, its side curtains rolled up between the bows': 'Camión de tropas: un camión con toldo de lona redondeado y las cortinas laterales enrolladas entre los arcos',
};
