from pathlib import Path
import json,hashlib,statistics,datetime,tarfile,collections,os
root=Path('/tmp/human-ai-selected-hud-v14-balance');source=Path('/tmp/human-ai-selected-hud-v14-balance-source');manifestPath=Path(str(source)+'-manifest.json');manifest=json.loads(manifestPath.read_text())
def sha(path):return hashlib.sha256(Path(path).read_bytes()).hexdigest()
def validate_rows(result,checkpoint):
 assert result['results']==checkpoint['results'],'Result/checkpoint rows differ'
 assert result['sourceSHA256']==checkpoint['sourceSHA256'],'Result/checkpoint source identity differs'
 assert len(result['results'])==30 and [r['match'] for r in result['results']]==list(range(1,31)),'Missing/duplicate/reordered match identifiers'
 assert [r['seed'] for r in result['results']]==list(range(1,31)),'Original seeds differ'
 assert all(r['seconds']==round(r['ticks']/20,3) for r in result['results']),'Tick/length reducer mismatch'
 ended=[r for r in result['results'] if r['winner'] is not None];wins=[r for r in ended if r['winner']>=0]
 counts={f:sum(r['winnerFaction']==f for r in wins) for f in ['USA','Germany','USSR']}
 expected={'ended':len(ended),'draws':len(ended)-len(wins),'timeouts':30-len(ended),'winsByFaction':counts,'medianSeconds':round(statistics.median([r['seconds'] for r in result['results']]),3),'medianEndedSeconds':round(statistics.median([r['seconds'] for r in ended]),3)}
 for name,value in expected.items():assert result[name]==value,f'Reducer mismatch {name}'
 for r in result['winsBySpawn']:assert r['wins']==sum(x['winnerSpawn']==r['spawn'] for x in wins),'Spawn reducer mismatch'
 for field,value in [('matches',30),('mode','classic'),('maxSeconds',2400),('map','default'),('army','standard'),('seed',1),('rotate',False),('seats',None)]:assert result[field]==value,field+' protocol mismatch'
 for field,value in [('matches',30),('mode','classic'),('map','default'),('army','standard'),('seed',1),('rotate',False),('seats',None),('factions',3)]:assert checkpoint['configuration'][field]==value,field+' checkpoint protocol mismatch'
 return {**expected,'decisiveWins':len(wins),'decisiveWinFractions':{f:n/len(wins) for f,n in counts.items()},'decisiveWinPercentages':{f:round(100*n/len(wins),2) for f,n in counts.items()},'maximumSeconds':max(r['seconds'] for r in result['results']),'endReasons':dict(collections.Counter(r['endReason'] for r in ended))}
v14Path=root/'classic.json';v14Checkpoint=root/'classic-checkpoint.json';v14=json.loads(v14Path.read_text());cp=json.loads(v14Checkpoint.read_text());after=validate_rows(v14,cp)
lines=[json.loads(x[7:]) for x in (root/'classic.log').read_text().splitlines() if x.startswith('RESULT ')];assert len(lines)==1 and lines[0]==v14,'Final log/report reducer differs'
for rel,expected in manifest['sourceSHA256'].items():assert sha(source/rel)==expected,'Archived source drift: '+rel
with tarfile.open(manifest['archivePath']) as archive:
 for rel,expected in manifest['sourceSHA256'].items():assert hashlib.sha256(archive.extractfile(source.name+'/'+rel).read()).hexdigest()==expected,'Tar source drift: '+rel
assert sha(manifest['archivePath'])==manifest['archiveSHA256'],'Tar archive changed'
for absolute,expected in v14['sourceSHA256'].items():assert manifest['sourceSHA256'][str(Path(absolute).relative_to(source))]==expected,'Runner/manifest source drift'
startupPaths=list(root.glob('classic-launch-*.json'));assert len(startupPaths)==1;startup=json.loads(startupPaths[0].read_text());affinity=json.loads((root/'classic-affinity-proof.json').read_text());assert startup['nodePid']==affinity['nodePid']==1178676;assert affinity['nodeStartTicks']=='10407892';assert ' '.join(startup['argv'])+' '==affinity['argv'];assert startup['preparedSourceFingerprintSHA256']==manifest['sourceFingerprintSHA256'];assert all(a==[0,2,8,10] for a in affinity['threadsAffinity'].values());assert v14['workers']==4 and v14['resumedMatches']==0
beforePath=Path('/tmp/human-ai-before-classic-corrected.json');beforeCheckpoint=Path('/tmp/human-ai-before-classic-corrected-checkpoint.json');before=json.loads(beforePath.read_text());bcp=json.loads(beforeCheckpoint.read_text());baseline=validate_rows(before,bcp);sharedDifferences=[];baselineArchive=Path('/tmp/human-ai-classic-baseline-source.tar')
with tarfile.open(baselineArchive) as archive:
 for absolute,expected in before['sourceSHA256'].items():
  rel=str(Path(absolute).relative_to(before['root']));assert hashlib.sha256(archive.extractfile(rel).read()).hexdigest()==expected,'Before tar source drift: '+rel
  current=manifest['sourceSHA256'].get(rel)
  if current and current!=expected:sharedDifferences.append({'path':rel,'correctedBeforeSHA256':expected,'historicalV14SHA256':current,'exactDiffArtifact':str(root/('before-v14-'+Path(rel).stem+'.diff'))})
for name,info in manifest['legacy']['hashes'].items():assert manifest['sourceSHA256']['tools/legacy-ai/'+name]==info['frozenSHA256']
assert manifest['sourceSHA256']['tools/ai-screen-v1-oracle.js']==manifest['screenV1Oracle']['frozenSHA256']
def gate(metrics):
 failures={f:p for f,p in metrics['decisiveWinPercentages'].items() if not .25<=metrics['decisiveWinFractions'][f]<=.42}
 return {'factionRangePercent':[25,42],'denominator':'Decisive wins, draws excluded','factionGate':'FAIL' if failures else 'PASS','outsideRange':failures,'allFinishGate':'PASS' if metrics['ended']==30 else 'FAIL'}
pairs=[{'match':a['match'],'seed':a['seed'],'beforeFaction':b['winnerFaction'],'v14Faction':a['winnerFaction'],'beforeSeconds':b['seconds'],'v14Seconds':a['seconds']} for b,a in zip(before['results'],v14['results'])]
events=[json.loads(x) for x in (root/'classic-completion-events.jsonl').read_text().splitlines()];assert len(events)==30 and {x['match'] for x in events}==set(range(1,31));finalStamp=max(x['observedAtUTC'] for x in events)
artifactPaths=[v14Path,v14Checkpoint,root/'classic.log',manifestPath,Path(manifest['archivePath']),source/'tools/ai-balance.mjs',startupPaths[0],root/'classic-affinity-proof.json',root/'classic-completion-events.jsonl',beforePath,beforeCheckpoint,baselineArchive,root/'before-v14-navigation.diff',root/'before-v14-sim.diff',Path(__file__)]
report={'generatedAtUTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'candidate':'selected-hud-v14','classification':'Historical V14 evidence, superseded by substantive V15 R5 source fixes','finalAcceptance':False,'overallHistoricalBalanceGate':'FAIL','historicalV14':{'metrics':after,'gates':gate(after),'startedAtUTC':startup['startedAtUTC'],'lastCompletionObservedAtUTC':finalStamp,'wallSeconds':v14['elapsedSeconds'],'workers':4,'actualAllThreadsAffinity':[0,2,8,10],'outerTimeout':None,'resumedMatches':0,'ownedNodePid':1178676,'ownedNodeStartTicks':'10407892','nodeExited':not Path('/proc/1178676').exists()},'correctedBefore':{'metrics':baseline,'gates':gate(baseline),'legacyCommit':manifest['legacy']['commit'],'workers':before['workers'],'resumedMatches':before['resumedMatches'],'finalResumedPhaseWallSeconds':before['elapsedSeconds'],'wallTimeCaveat':'Corrected-before elapsed time covers its final resumed 26 rows, while V14 elapsed time covers all 30. These wall durations are not directly comparable.'},'comparison':{'sameOriginalSeeds':True,'allSeeds':list(range(1,31)),'sameMapModeArmyFactionCountAndLimits':True,'winsDelta':{f:after['winsByFaction'][f]-baseline['winsByFaction'][f] for f in after['winsByFaction']},'percentagePointDelta':{f:round(100*(after['decisiveWinFractions'][f]-baseline['decisiveWinFractions'][f]),2) for f in after['winsByFaction']},'medianSecondsDelta':after['medianSeconds']-baseline['medianSeconds'],'pairedMatches':pairs,'sharedSourceDifferences':sharedDifferences,'sourceDifferenceCaveat':'Archived baseline and V14 share the exact runner and ordinary match configuration, but navigation and initial observed-wall source differ. Exact optimization diffs are retained. This audit does not independently establish their behavioral equivalence or attribute faction changes solely to AI.'},'sourceEvidence':{'archiveFilesVerified':len(manifest['sourceSHA256']),'v14RunnerFilesVerified':len(v14['sourceSHA256']),'correctedBeforeRunnerFilesVerified':len(before['sourceSHA256']),'sourceFingerprintSHA256':manifest['sourceFingerprintSHA256'],'coreHashes':{k:v for k,v in manifest['sourceSHA256'].items() if k.startswith('shared/ai') or k in ['shared/sim.js','shared/navigation.js','tools/ai-balance.mjs']},'legacy':manifest['legacy'],'screenV1Oracle':manifest['screenV1Oracle'],'oracleUsage':'Archived provenance only; the balance runner did not import the measurement oracle.'},'checks':{'rawResultMatchesCheckpoint':True,'rawResultMatchesLogReducer':True,'exactThirtyUniqueOriginalSeeds':True,'ticksMatchSimulatedSeconds':True,'independentReducerMatches':True,'noRowsTrimmedOrOmitted':True,'runtimeAndTarHashesMatchFrozenManifest':True,'baselineSourceTarMatchesResultHashes':True,'startupAndAffinityIdentityAgree':True},'artifactsSHA256':{str(p):sha(p) for p in artifactPaths},'launchPolicy':'No new balance batches until the final new source freeze and explicit root CPU clearance.'}
reportPath=root/'classic-historical-final-report.json';reportPath.write_text(json.dumps(report,indent=2)+'\n')
text=f"Historical V14 Classic balance verification\n\nV14 completed all 30 original seeds 1 through 30. It recorded USA {after['winsByFaction']['USA']}, Germany {after['winsByFaction']['Germany']}, USSR {after['winsByFaction']['USSR']} and {after['draws']} draw. All matches finished with {after['timeouts']} timeouts; median length was {after['medianSeconds']} simulated seconds.\n\nFaction gate: FAIL. Decisive win shares were USA {after['decisiveWinPercentages']['USA']:.2f}%, Germany {after['decisiveWinPercentages']['Germany']:.2f}% and USSR {after['decisiveWinPercentages']['USSR']:.2f}%, against the required 25 to 42% range. USA was below the floor and USSR above the ceiling.\n\nCorrected before: USA 12, Germany 7, USSR 10 and one draw. Shares were 41.38%, 24.14% and 34.48%. It also finished 30/30 with no timeouts and median 1600 seconds. Its Germany share was below 25%.\n\nThe raw reports, checkpoints, reducer output and all original rows agree. This audit verified all 42 archived V14 files, 32 V14 runner fingerprints and 23 corrected-before runner fingerprints. Navigation and initial observed-wall optimization source differences are preserved as exact diffs; this audit does not independently prove their equivalence.\n\nV14 is historical and superseded by substantive V15 R5 fixes. It does not certify the new runtime. No new balance campaign is authorized by this report.\n"
(root/'classic-historical-final-report.md').write_text(text);index={'generatedAtUTC':report['generatedAtUTC'],'reportSHA256':sha(reportPath),'markdownSHA256':sha(root/'classic-historical-final-report.md'),'artifactSHA256':report['artifactsSHA256']};(root/'classic-historical-hash-index.json').write_text(json.dumps(index,indent=2)+'\n')
state=json.loads((root/'campaign-state.json').read_text());state.update({'status':'Historical V14 completed, superseded by V15 R5','classicCompleted':30,'classicHistoricalFactionGate':'FAIL','finalAcceptance':False,'historicalReport':str(reportPath)});(root/'campaign-state.json').write_text(json.dumps(state,indent=2)+'\n')
print(json.dumps({'report':str(reportPath),'reportSHA256':sha(reportPath),'v14':after,'v14Gates':gate(after),'correctedBefore':baseline,'baselineGates':gate(baseline),'verifiedArchiveFiles':len(manifest['sourceSHA256']),'sourceDifferences':[x['path'] for x in sharedDifferences]}))
