from pathlib import Path
import os,subprocess,tempfile,json,yaml
repo=Path('/home/judiazm/.t3/worktrees/ww2-rts/ai-human-commander');candidate=Path('/tmp/human-ai-ci-proposal/.github/workflows/tests.yml');old=yaml.load((repo/'.github/workflows/tests.yml').read_text(),Loader=yaml.BaseLoader);new=yaml.load(candidate.read_text(),Loader=yaml.BaseLoader);job=new['jobs']['game-tests'];steps=job['steps'];by_name={step.get('name'):step for step in steps};results=[]
assert new['name']==old['name'] and new['on']==old['on'] and new['permissions']==old['permissions'] and new['concurrency']==old['concurrency'];assert job['runs-on']==old['jobs']['game-tests']['runs-on'];assert job['defaults']['run']['shell']=='bash';assert int(job['timeout-minutes'])==60;assert int(by_name['Run full game regression suite']['timeout-minutes'])==55;assert job['steps'][1]['with']['node-version']=='24';assert not any('continue-on-error'in step for step in steps)
assert by_name['Install dependencies']['run']=='npm ci --ignore-scripts --no-audit --no-fund';assert by_name['Run full game regression suite']['run'].startswith('node test.js 2>&1 | tee ');assert by_name['Run world rendering checks']['run'].startswith('node test-world.js 2>&1 | tee ');assert by_name['Save regression proof']['if']=='${{ always() }}';assert by_name['Save regression proof']['with']['if-no-files-found']=='error';results.append({'workflowContract':'same event, permission, concurrency, runner, Node, dependency and native gate commands; no continue-on-error'})
root=Path(tempfile.mkdtemp(prefix='human-ai-ci-wrapper-',dir='/tmp'));proof=root/'proof';proof.mkdir();(root/'package.json').write_text('{"type":"module"}\n');subprocess.run(['git','init','-q'],cwd=root,check=True);subprocess.run(['git','add','package.json'],cwd=root,check=True)
(root/'directory').mkdir();(root/'directory-link').symlink_to('directory',target_is_directory=True);(root/'dangling-link').symlink_to('absent');subprocess.run(['git','add','directory-link','dangling-link'],cwd=root,check=True)
def execute(script,cwd=root):
 return subprocess.run(['/bin/bash','--noprofile','--norc','-eo','pipefail','-c',script],cwd=cwd,env={**os.environ,'GAME_TEST_PROOF':str(proof)},text=True,capture_output=True,timeout=15)
manifest=by_name['Record test source and runtime']['run'][by_name['Record test source and runtime']['run'].index('git ls-files -z'):];guard=by_name['Verify tested source stayed unchanged']['run'];pipeline=by_name['Run full game regression suite']['run']
for fails in[False,True]:
 (root/'test.js').write_text("import assert from 'node:assert/strict';\n"+("assert.fail('CI wrapper failure fixture');\n"if fails else"assert.equal(2+2,4);console.log('CI wrapper success fixture');\n"));subprocess.run(['git','add','test.js'],cwd=root,check=True);assert execute(manifest).returncode==0;run=execute(pipeline);assert run.returncode==(1 if fails else 0);log=(proof/'test.log').read_text();assert ('CI wrapper failure fixture' if fails else'CI wrapper success fixture')in log;assert execute(guard).returncode==0;results.append({'intentionalAssertionFailure':fails,'pipelineExit':run.returncode,'stdoutAndStderrRetained':True,'unchangedSourceGuard':True})
(root/'test.js').write_text('// deliberate tracked-source mutation\n');changed=execute(guard);assert changed.returncode==1;assert (proof/'source.diff').read_text();results.append({'actualTrackedSourceMutation':'fails hash comparison and retains diff','guardExit':changed.returncode})
(root/'dangling-link').unlink();(root/'dangling-link').symlink_to('different-absent');linkChanged=execute(guard);assert linkChanged.returncode==1;results.append({'symlinkDirectoryAndDanglingLinks':'captured without following links; target changes fail source guard'})
actual=execute(by_name['Record test source and runtime']['run'],repo);assert actual.returncode==0,actual.stderr;assert (proof/'runtime.txt').read_text().splitlines()[0].endswith(subprocess.check_output(['git','rev-parse','HEAD'],cwd=repo,text=True).strip());results.append({'actualRuntimeAndSourceCapture':'executed original proposed workflow command','node':subprocess.check_output(['node','--version'],text=True).strip(),'trackedFiles':len((proof/'source-before.sha256').read_text().splitlines())})
world=execute(by_name['Run world rendering checks']['run'],repo);assert world.returncode==0,world.stderr;results.append({'actualNodeTestWorld':'passes with exact proposed pipefail logging wrapper','logBytes':(proof/'test-world.log').stat().st_size})
Path('/tmp/human-ai-ci-validation/proof.json').write_text(json.dumps(results,indent=2)+'\n');print(json.dumps(results,indent=2));print('Fixture artifacts:',root)
